### Use splink to test entity resolution on dataset_1 and dataset_2

In [ ]:
pip install splink

In [ ]:
pip install pandas

In [8]:
import pandas as pd

In [9]:
# Load the dataset_1.csv
dataset_1 = pd.read_csv('datasets/dataset_1.csv')

# Display the first few rows of the DataFrame to verify that the data has been loaded correctly
dataset_1.head(5)

,unique_id,first_name,last_name,phone_number,email,street_address,city,state,zip_code,country,fatca_id,giin
0,1,Danielle,Ford,1352724631,wilkinssara@example.org,639 Gregory Parkways,Castilloville,Utah,89488,Fiji,104332,949993.93305.SL.728
1,2,James,Reed,558666300,tyler63@example.net,962 Cunningham Throughway,Taylorburgh,Kansas,47050,Monaco,181960,975267.72233.LE.604
2,3,Brian,Moss,3493371326,coreycarlson@example.org,21295 Michael Lock,Jasonview,Colorado,4185,Congo,13389,633312.79757.BR.660
3,4,Micheal,Hudson,821435310,pguerrero@example.com,640 Gibson Road,Munozview,Georgia,20729,Georgia,83863,965699.98808.SL.770
4,5,Jacqueline,Tran,3204000112,lmcgee@example.org,43945 Anderson Views,Mcconnelltown,Montana,77920,Guam,794026,388608.68034.SS.644

In [10]:
# Load the dataset_2.csv
dataset_2 = pd.read_csv('datasets/dataset_2.csv')

# Display the first few rows of the DataFrame to verify that the data has been loaded correctly
dataset_2.head(5)

,unique_id,first_name,last_name,phone_number,email,street_address,city,state,zip_code,country,fatca_id,giin
0,1,D,Ford,1352724631,wilkinssara@example.org,639 Gregory Parkways,Castilloville,Utah,89488,Fiji,104332,949993.93305.SL.728
1,2,J,Reed,558666300,tyler63@example.net,962 Cunningham Throughway,Taylorburgh,Kansas,47050,Monaco,181960,975267.72233.LE.604
2,3,B,Moss,3493371326,coreycarlson@example.org,21295 Michael Lock,Jasonview,Colorado,4185,Congo,13389,633312.79757.BR.660
3,4,M,Hudson,821435310,pguerrero@example.com,640 Gibson Road,Munozview,Georgia,20729,Georgia,83863,965699.98808.SL.770
4,5,J,Tran,3204000112,lmcgee@example.org,43945 Anderson Views,Mcconnelltown,Montana,77920,Guam,794026,388608.68034.SS.644

In [12]:
# Explore amount of missing data because columns with higher levels of null values are less useful for data linking
# Missing data for dataset_1
from splink.exploratory import completeness_chart
from splink import DuckDBAPI
db_api = DuckDBAPI()
completeness_chart(dataset_1, db_api=db_api)

alt.LayerChart(...)

In [14]:
# Explore amount of missing data because columns with higher levels of null values are less useful for data linking
# Missing data for dataset_2
from splink.exploratory import completeness_chart
from splink import DuckDBAPI
db_api = DuckDBAPI()
completeness_chart(dataset_2, db_api=db_api)

alt.LayerChart(...)

## Analyze distribution of data:

In [17]:
# Columns with higher cardinality (number of distinct values) are usually more useful for data linking
# Skew of values are important. A column that has a majority of same values ( ex. cities is 75% London) 
# is less useful for linkage than if citites were equally distributed

In [19]:
# Analyze distribution of distinct values in each column for dataset_1
from splink.exploratory import profile_columns
profile_columns(dataset_1, db_api=DuckDBAPI(), top_n=10, bottom_n=5)

alt.VConcatChart(...)

In [20]:
# Analyze distribution of distinct values in each column for dataset_2
from splink.exploratory import profile_columns
profile_columns(dataset_2, db_api=DuckDBAPI(), top_n=10, bottom_n=5)

alt.VConcatChart(...)