## Create fake data for Brockman Entity Resolution

Amanda Rodgers
Notebook started: 2/6/25

In [1]:
import pandas as pd
import random
import numpy as np
from faker import Faker

In [2]:
# Initialize Faker
fake = Faker()

# Seed for reproducibility
random.seed(42)
np.random.seed(42)

### Create fake GIIN's

Example GIIN: 123456.12345.12.123

See: https://www.irs.gov/businesses/corporations/fatca-registration-and-ffi-list-giin-composition-information

123456 is the FATCA ID  
12345 is the Sponsoring Entity    
12 is the Category Code   
123 is the Country/Jurisdiction code

In [3]:
# Create fake GIIN numbers
def generate_fake_giin():

    codes = ['LE', 'SL', 'ME', 'BR', 'SP', 'SF', 'SD', 'SS', 'SB']
    
    # Generate the FATCA ID (6 digits)
    fatca_id = ''.join([str(random.randint(0, 9)) for _ in range(6)])
    
    # Generate the Sponsoring Entity (5 digits)
    sponsoring_entity = ''.join([str(random.randint(0, 9)) for _ in range(5)])
    
    # Generate the Category Code (2 letters, ISO 3166-1 alpha-2 code)
    category_code = random.choice(codes)
    
    # Generate the Country Code (3 digits)
    country_code = ''.join([str(random.randint(0, 9)) for _ in range(3)])
    
    # Combine all parts to form the GIIN
    giin = f"{fatca_id}.{sponsoring_entity}.{category_code}.{country_code}"
    
    return giin

# Generate a fake GIIN
# fake_giin = generate_fake_giin()
# print(fake_giin)

### Create fake FATCA ID

In [4]:
def fatca_id():
    # Generate a string of 6 random digits
    id_str = ''.join([str(random.randint(0, 9)) for _ in range(6)])
    return id_str

# Generate a FATCA ID
# generated_fatca_id = fatca_id()
# print(generated_fatca_id)

### Create other fake PII

In [5]:
# Create first name

def generate_random_first_name():
    first_name = fake.first_name()
    return first_name

# Generate a random first name
# random_first_name = generate_random_first_name()
# print(random_first_name)

In [6]:
# Create last name

def generate_random_last_name():
    last_name = fake.last_name()
    return last_name

# Generate a random last name
random_last_name = generate_random_last_name()
print(random_last_name)

Hill

In [7]:
# Create fake phone number in format (xxx) xxx-xxxx
# Can change format of phone numbers later if needed for country codes and extensions

def generate_formatted_phone_number():
    phone_number = fake.numerify('(###) ###-####')
    return phone_number

# Generate a formatted fake phone number
formatted_phone_number = generate_formatted_phone_number()
print(formatted_phone_number)

(912) 552-2050

In [8]:
# Create fake email

def generate_fake_email():
    email = fake.email()
    return email

# Generate a fake email address
# fake_email = generate_fake_email()
# print(fake_email)

In [9]:
# Create fake street address

def generate_street_address():
    building_number = fake.building_number()
    street_name = fake.street_name()
    street_address = f"{building_number} {street_name}"
    return street_address

# Generate a street address
# street_address = generate_street_address()
# print(street_address)

In [10]:
# Create fake city name

def generate_single_word_city():
    while True:
        city = fake.city()
        if len(city.split()) == 1:
            return city

# Generate a single-word fake city name
# single_word_city = generate_single_word_city()
# print(single_word_city)

In [11]:
# Create fake state

def generate_fake_state():
    state = fake.state()
    return state

# Generate a fake state name
# fake_state = generate_fake_state()
# print(fake_state)

In [12]:
# Create fake zip

def generate_fake_zip_code():
    zip_code = fake.zipcode()
    return zip_code

# Generate a fake ZIP code
# fake_zip_code = generate_fake_zip_code()
# print(fake_zip_code)

In [13]:
# Create fake country

def generate_fake_country():
    country = fake.country()
    return country

# Generate a fake country name
fake_country = generate_fake_country()
print(fake_country)

Brazil

In [14]:
# Create fake tax country

def tax_country():
    country = fake.country()
    return country

# Generate a random country name
random_country = tax_country()
print(random_country)

Burundi

### Create dataframe

In [15]:
# Create a DataFrame with 1000 rows
data = {
    'first_name': [generate_random_first_name() for _ in range(1000)],
    'last_name': [generate_random_last_name() for _ in range(1000)],
    'phone_number': [generate_formatted_phone_number() for _ in range(1000)],
    'email': [generate_fake_email() for _ in range(1000)],
    'street_address': [generate_street_address() for _ in range(1000)],
    'city': [generate_single_word_city() for _ in range(1000)],
    'state': [generate_fake_state() for _ in range(1000)],
    'zip_code': [generate_fake_zip_code() for _ in range(1000)],
    'country': [tax_country() for _ in range(1000)],
    'fatca_id': [fatca_id() for _ in range(1000)], 
    'giin': [generate_fake_giin() for _ in range(1000)]
}

df = pd.DataFrame(data)

# Display the first few rows of the DataFrame
print(df.head())

   first_name last_name    phone_number                     email  \
0    Danielle      Ford  (135) 272-4631   wilkinssara@example.org
1       James      Reed  (055) 866-6300       tyler63@example.net
2       Brian      Moss  (349) 337-1326  coreycarlson@example.org
3     Micheal    Hudson  (082) 143-5310     pguerrero@example.com
4  Jacqueline      Tran  (320) 400-0112        lmcgee@example.org

              street_address           city     state zip_code  country  \
0       639 Gregory Parkways  Castilloville      Utah    89488     Fiji
1  962 Cunningham Throughway    Taylorburgh    Kansas    47050   Monaco
2         21295 Michael Lock      Jasonview  Colorado    04185    Congo
3            640 Gibson Road      Munozview   Georgia    20729  Georgia
4       43945 Anderson Views  Mcconnelltown   Montana    77920     Guam

  fatca_id                 giin
0   104332  949993.93305.SL.728
1   181960  975267.72233.LE.604
2   013389  633312.79757.BR.660
3   083863  965699.98808.SL.770
4   794026  388608.68034.SS.644

In [16]:
# Check data
df.head(10)

,first_name,last_name,phone_number,email,street_address,city,state,zip_code,country,fatca_id,giin
0,Danielle,Ford,(135) 272-4631,wilkinssara@example.org,639 Gregory Parkways,Castilloville,Utah,89488,Fiji,104332,949993.93305.SL.728
1,James,Reed,(055) 866-6300,tyler63@example.net,962 Cunningham Throughway,Taylorburgh,Kansas,47050,Monaco,181960,975267.72233.LE.604
2,Brian,Moss,(349) 337-1326,coreycarlson@example.org,21295 Michael Lock,Jasonview,Colorado,04185,Congo,013389,633312.79757.BR.660
3,Micheal,Hudson,(082) 143-5310,pguerrero@example.com,640 Gibson Road,Munozview,Georgia,20729,Georgia,083863,965699.98808.SL.770
4,Jacqueline,Tran,(320) 400-0112,lmcgee@example.org,43945 Anderson Views,Mcconnelltown,Montana,77920,Guam,794026,388608.68034.SS.644
5,Jessica,Long,(175) 402-4160,upadilla@example.com,46939 Vicki Vista,Wallacemouth,Maine,26474,Albania,542351,726490.82771.SB.129
6,Brandon,Owens,(728) 408-5582,ecarson@example.com,14234 Brittany Groves,Normaland,Idaho,74678,Argentina,161559,826657.02793.SS.145
7,David,Gordon,(296) 565-4013,rvasquez@example.com,28399 Moore Plains,Blakeberg,Nevada,99151,Tunisia,407816,211175.18689.ME.686
8,Jennifer,Santos,(883) 776-0149,rhines@example.com,01900 Mueller Ville,Kevinport,Louisiana,31360,Libyan Arab Jamahiriya,184959,025922.22064.SP.742
9,Max,Perez,(491) 051-8511,gonzalesmelissa@example.org,958 Williams Street,Edwardsfurt,Florida,17820,Cape Verde,310341,123094.07778.LE.973

In [17]:
# Add a unique_id column ( per Splink requirements) and make it the first column
def add_unique_id(df):
    df.insert(0, 'unique_id', range(1, len(df) + 1))
    return df

# Add the unique_id column to the DataFrame
df = add_unique_id(df)

# Display the first few rows of the DataFrame
df.head(10)

,unique_id,first_name,last_name,phone_number,email,street_address,city,state,zip_code,country,fatca_id,giin
0,1,Danielle,Ford,(135) 272-4631,wilkinssara@example.org,639 Gregory Parkways,Castilloville,Utah,89488,Fiji,104332,949993.93305.SL.728
1,2,James,Reed,(055) 866-6300,tyler63@example.net,962 Cunningham Throughway,Taylorburgh,Kansas,47050,Monaco,181960,975267.72233.LE.604
2,3,Brian,Moss,(349) 337-1326,coreycarlson@example.org,21295 Michael Lock,Jasonview,Colorado,04185,Congo,013389,633312.79757.BR.660
3,4,Micheal,Hudson,(082) 143-5310,pguerrero@example.com,640 Gibson Road,Munozview,Georgia,20729,Georgia,083863,965699.98808.SL.770
4,5,Jacqueline,Tran,(320) 400-0112,lmcgee@example.org,43945 Anderson Views,Mcconnelltown,Montana,77920,Guam,794026,388608.68034.SS.644
5,6,Jessica,Long,(175) 402-4160,upadilla@example.com,46939 Vicki Vista,Wallacemouth,Maine,26474,Albania,542351,726490.82771.SB.129
6,7,Brandon,Owens,(728) 408-5582,ecarson@example.com,14234 Brittany Groves,Normaland,Idaho,74678,Argentina,161559,826657.02793.SS.145
7,8,David,Gordon,(296) 565-4013,rvasquez@example.com,28399 Moore Plains,Blakeberg,Nevada,99151,Tunisia,407816,211175.18689.ME.686
8,9,Jennifer,Santos,(883) 776-0149,rhines@example.com,01900 Mueller Ville,Kevinport,Louisiana,31360,Libyan Arab Jamahiriya,184959,025922.22064.SP.742
9,10,Max,Perez,(491) 051-8511,gonzalesmelissa@example.org,958 Williams Street,Edwardsfurt,Florida,17820,Cape Verde,310341,123094.07778.LE.973

In [18]:
# Reassign to original_df
original_df = df

In [19]:
original_df.head(10)

,unique_id,first_name,last_name,phone_number,email,street_address,city,state,zip_code,country,fatca_id,giin
0,1,Danielle,Ford,(135) 272-4631,wilkinssara@example.org,639 Gregory Parkways,Castilloville,Utah,89488,Fiji,104332,949993.93305.SL.728
1,2,James,Reed,(055) 866-6300,tyler63@example.net,962 Cunningham Throughway,Taylorburgh,Kansas,47050,Monaco,181960,975267.72233.LE.604
2,3,Brian,Moss,(349) 337-1326,coreycarlson@example.org,21295 Michael Lock,Jasonview,Colorado,04185,Congo,013389,633312.79757.BR.660
3,4,Micheal,Hudson,(082) 143-5310,pguerrero@example.com,640 Gibson Road,Munozview,Georgia,20729,Georgia,083863,965699.98808.SL.770
4,5,Jacqueline,Tran,(320) 400-0112,lmcgee@example.org,43945 Anderson Views,Mcconnelltown,Montana,77920,Guam,794026,388608.68034.SS.644
5,6,Jessica,Long,(175) 402-4160,upadilla@example.com,46939 Vicki Vista,Wallacemouth,Maine,26474,Albania,542351,726490.82771.SB.129
6,7,Brandon,Owens,(728) 408-5582,ecarson@example.com,14234 Brittany Groves,Normaland,Idaho,74678,Argentina,161559,826657.02793.SS.145
7,8,David,Gordon,(296) 565-4013,rvasquez@example.com,28399 Moore Plains,Blakeberg,Nevada,99151,Tunisia,407816,211175.18689.ME.686
8,9,Jennifer,Santos,(883) 776-0149,rhines@example.com,01900 Mueller Ville,Kevinport,Louisiana,31360,Libyan Arab Jamahiriya,184959,025922.22064.SP.742
9,10,Max,Perez,(491) 051-8511,gonzalesmelissa@example.org,958 Williams Street,Edwardsfurt,Florida,17820,Cape Verde,310341,123094.07778.LE.973

In [20]:
# Make dataframe into csv file and store in dataset folder
# Ensure the 'dataset' folder exists or create it
import os

if not os.path.exists('datasets'):
    os.makedirs('datasets')

# Save the DataFrame as a CSV file in the 'dataset' folder
csv_file_path = os.path.join('datasets', 'original_df.csv')
original_df.to_csv(csv_file_path, index=False)