## Clean fake dataset for Splink

Amanda Rodgers  
Notebook created: 2.6.2025

In [1]:
import pandas as pd
import numpy as np

In [2]:
# Define the path to the CSV file
csv_file_path = 'datasets/original_df.csv'

# Read the CSV file into a DataFrame
original_df = pd.read_csv(csv_file_path)

# Display the first few rows of the DataFrame to verify
original_df.head(10)

,unique_id,first_name,last_name,phone_number,email,street_address,city,state,zip_code,country,fatca_id,giin
0,1,Danielle,Ford,(135) 272-4631,wilkinssara@example.org,639 Gregory Parkways,Castilloville,Utah,89488,Fiji,104332,949993.93305.SL.728
1,2,James,Reed,(055) 866-6300,tyler63@example.net,962 Cunningham Throughway,Taylorburgh,Kansas,47050,Monaco,181960,975267.72233.LE.604
2,3,Brian,Moss,(349) 337-1326,coreycarlson@example.org,21295 Michael Lock,Jasonview,Colorado,4185,Congo,13389,633312.79757.BR.660
3,4,Micheal,Hudson,(082) 143-5310,pguerrero@example.com,640 Gibson Road,Munozview,Georgia,20729,Georgia,83863,965699.98808.SL.770
4,5,Jacqueline,Tran,(320) 400-0112,lmcgee@example.org,43945 Anderson Views,Mcconnelltown,Montana,77920,Guam,794026,388608.68034.SS.644
5,6,Jessica,Long,(175) 402-4160,upadilla@example.com,46939 Vicki Vista,Wallacemouth,Maine,26474,Albania,542351,726490.82771.SB.129
6,7,Brandon,Owens,(728) 408-5582,ecarson@example.com,14234 Brittany Groves,Normaland,Idaho,74678,Argentina,161559,826657.02793.SS.145
7,8,David,Gordon,(296) 565-4013,rvasquez@example.com,28399 Moore Plains,Blakeberg,Nevada,99151,Tunisia,407816,211175.18689.ME.686
8,9,Jennifer,Santos,(883) 776-0149,rhines@example.com,01900 Mueller Ville,Kevinport,Louisiana,31360,Libyan Arab Jamahiriya,184959,025922.22064.SP.742
9,10,Max,Perez,(491) 051-8511,gonzalesmelissa@example.org,958 Williams Street,Edwardsfurt,Florida,17820,Cape Verde,310341,123094.07778.LE.973

In [3]:
# Remove Unnamed: column
def remove_unnamed_column(df):
    # Identify columns that start with 'Unnamed:'
    unnamed_cols = [col for col in df.columns if col.startswith('Unnamed:')]
    # Drop the 'Unnamed:' columns if they exist
    df = df.drop(columns=unnamed_cols)
    return df

In [4]:
# Remove the 'Unnamed:' column(s) if they exist
original_df = remove_unnamed_column(original_df)

# Display the first few rows of the DataFrame to verify
original_df.head(5)

,unique_id,first_name,last_name,phone_number,email,street_address,city,state,zip_code,country,fatca_id,giin
0,1,Danielle,Ford,(135) 272-4631,wilkinssara@example.org,639 Gregory Parkways,Castilloville,Utah,89488,Fiji,104332,949993.93305.SL.728
1,2,James,Reed,(055) 866-6300,tyler63@example.net,962 Cunningham Throughway,Taylorburgh,Kansas,47050,Monaco,181960,975267.72233.LE.604
2,3,Brian,Moss,(349) 337-1326,coreycarlson@example.org,21295 Michael Lock,Jasonview,Colorado,4185,Congo,13389,633312.79757.BR.660
3,4,Micheal,Hudson,(082) 143-5310,pguerrero@example.com,640 Gibson Road,Munozview,Georgia,20729,Georgia,83863,965699.98808.SL.770
4,5,Jacqueline,Tran,(320) 400-0112,lmcgee@example.org,43945 Anderson Views,Mcconnelltown,Montana,77920,Guam,794026,388608.68034.SS.644

## Splink data prep requirements

- If comparing two databases, the columns being compared must exact same heading name
- Values of columns must be in the same format. 
- Null cells must be true nulls and not empty strings or NaN
- Trim leading and trailing whitespace
- Remove special characters
- Standardize date formats as strings like yyyy-mm-dd
- Replace abreviations with full words. Ex. St. becomes Street

In [5]:
# Make sure null values are all true nulls
def standardize_missing_values(df):
    """
    Standardize cells containing 'nan', 'Nan', 'None', or other representations of missing values to true null values (NaN).
    """
    # Replace 'nan', 'Nan', 'None', and other representations with np.nan
    df.replace(['nan', 'Nan', 'None', 'xx', None], np.nan, inplace=True)
    
    return df

original_df = standardize_missing_values(original_df)

In [6]:
def count_nulls(df):
    """
    This function takes a pandas DataFrame as input and returns a Series
    containing the count of null values in each column.
    
    Parameters:
    df (pd.DataFrame): The DataFrame to count null values in.
    
    Returns:
    pd.Series: A Series with the count of null values for each column.
    """
    return df.isnull().sum()

In [7]:
print(count_nulls(original_df))

unique_id         0
first_name        0
last_name         0
phone_number      0
email             0
street_address    0
city              0
state             0
zip_code          0
country           0
fatca_id          0
giin              0
dtype: int64

In [8]:
# Clean phone numbers to just digits
import re

def clean_phone_number(phone_number):
    """
    This function takes a phone number string as input and returns a cleaned version
    with only numeric characters.
    
    Parameters:
    phone_number (str): The phone number to clean.
    
    Returns:
    str: The cleaned phone number.
    """
    return re.sub(r'\D', '', phone_number)

original_df['phone_number'] = original_df['phone_number'].apply(clean_phone_number)
original_df.head(5)

,unique_id,first_name,last_name,phone_number,email,street_address,city,state,zip_code,country,fatca_id,giin
0,1,Danielle,Ford,1352724631,wilkinssara@example.org,639 Gregory Parkways,Castilloville,Utah,89488,Fiji,104332,949993.93305.SL.728
1,2,James,Reed,0558666300,tyler63@example.net,962 Cunningham Throughway,Taylorburgh,Kansas,47050,Monaco,181960,975267.72233.LE.604
2,3,Brian,Moss,3493371326,coreycarlson@example.org,21295 Michael Lock,Jasonview,Colorado,4185,Congo,13389,633312.79757.BR.660
3,4,Micheal,Hudson,0821435310,pguerrero@example.com,640 Gibson Road,Munozview,Georgia,20729,Georgia,83863,965699.98808.SL.770
4,5,Jacqueline,Tran,3204000112,lmcgee@example.org,43945 Anderson Views,Mcconnelltown,Montana,77920,Guam,794026,388608.68034.SS.644

In [9]:
# Cleaned emails
def clean_email(email):
    """
    This function takes an email address string as input and returns a cleaned version
    with consistent formatting.
    
    Parameters:
    email (str): The email address to clean.
    
    Returns:
    str: The cleaned email address.
    """
    # Convert to lowercase
    email = email.lower()
    
    # Remove leading and trailing whitespace
    email = email.strip()
    
    # Validate email format (simple regex)
    if re.match(r'^[a-zA-Z0-9._%+-]+@[a-zA-Z0-9.-]+\.[a-zA-Z]{2,}$', email):
        return email
    else:
        return None

original_df['email'] = original_df['email'].apply(clean_email)
original_df.head(5)

,unique_id,first_name,last_name,phone_number,email,street_address,city,state,zip_code,country,fatca_id,giin
0,1,Danielle,Ford,1352724631,wilkinssara@example.org,639 Gregory Parkways,Castilloville,Utah,89488,Fiji,104332,949993.93305.SL.728
1,2,James,Reed,0558666300,tyler63@example.net,962 Cunningham Throughway,Taylorburgh,Kansas,47050,Monaco,181960,975267.72233.LE.604
2,3,Brian,Moss,3493371326,coreycarlson@example.org,21295 Michael Lock,Jasonview,Colorado,4185,Congo,13389,633312.79757.BR.660
3,4,Micheal,Hudson,0821435310,pguerrero@example.com,640 Gibson Road,Munozview,Georgia,20729,Georgia,83863,965699.98808.SL.770
4,5,Jacqueline,Tran,3204000112,lmcgee@example.org,43945 Anderson Views,Mcconnelltown,Montana,77920,Guam,794026,388608.68034.SS.644

In [11]:
# Save dataset_2 to a csv
import os

def save_dataframe_to_csv(df, filename='dataset_2', folder='datasets'):
    """
    This function takes a pandas DataFrame and saves it as a CSV file
    in the specified folder with the given filename.
    
    Parameters:
    df (pd.DataFrame): The DataFrame to save.
    filename (str): The name of the file (without extension). Default is 'dataset1'.
    folder (str): The folder where the file will be saved. Default is 'datasets'.
    
    Returns:
    str: The path to the saved file.
    """
    # Ensure the folder exists
    if not os.path.exists(folder):
        os.makedirs(folder)
    
    # Create the full file path
    file_path = os.path.join(folder, f"{filename}.csv")
    
    # Save the DataFrame to a CSV file
    df.to_csv(file_path, index=False)
    
    return file_path

file_path = save_dataframe_to_csv(original_df)
print(f"DataFrame saved to: {file_path}")

DataFrame saved to: datasets\dataset_2.csv