### Create dataset_2

In [ ]:
# Will differ from dataset_1 by having 10% of first names just being first letter of first name

In [1]:
import pandas as pd
import random
import numpy as np
from faker import Faker

In [3]:
# Load unique_people_transactions.csv ( 1000 unique people and transactions)
df = pd.read_csv('datasets/dataset_1.csv')

In [4]:
df.head(5)

,unique_id,first_name,last_name,phone_number,email,street_address,city,state,zip_code,country,fatca_id,giin
0,1,Danielle,Ford,1352724631,wilkinssara@example.org,639 Gregory Parkways,Castilloville,Utah,89488,Fiji,104332,949993.93305.SL.728
1,2,James,Reed,558666300,tyler63@example.net,962 Cunningham Throughway,Taylorburgh,Kansas,47050,Monaco,181960,975267.72233.LE.604
2,3,Brian,Moss,3493371326,coreycarlson@example.org,21295 Michael Lock,Jasonview,Colorado,4185,Congo,13389,633312.79757.BR.660
3,4,Micheal,Hudson,821435310,pguerrero@example.com,640 Gibson Road,Munozview,Georgia,20729,Georgia,83863,965699.98808.SL.770
4,5,Jacqueline,Tran,3204000112,lmcgee@example.org,43945 Anderson Views,Mcconnelltown,Montana,77920,Guam,794026,388608.68034.SS.644

In [13]:
# Make dataset_2 by modifying the first 100 rows of dataset_1 and changing the first_name column to the first character in the string
def modify_first_name_by_unique_id(df):
    """
    Modify the rows with unique_id from 1 to 100 in the DataFrame, changing the `first_name` column to contain only the first character
    of the original `first_name`.

    Parameters:
    df (pd.DataFrame): The input DataFrame with columns `first_name` and `unique_id`.

    Returns:
    pd.DataFrame: The modified DataFrame.
    """
    # Filter the DataFrame to get rows with unique_id from 1 to 100
    rows_to_modify = df[df['unique_id'].between(1, 100)].index
    
    # Modify the `first_name` column for the selected rows
    df.loc[rows_to_modify, 'first_name'] = df.loc[rows_to_modify, 'first_name'].str[0]
    
    return df

# Modify the DataFrame
dataset_2 = modify_first_name_by_unique_id(df)
dataset_2.head(105) # Print the top 105 rows to see the changes

,unique_id,first_name,last_name,phone_number,email,street_address,city,state,zip_code,country,fatca_id,giin
0,1,D,Ford,1352724631,wilkinssara@example.org,639 Gregory Parkways,Castilloville,Utah,89488,Fiji,104332,949993.93305.SL.728
1,2,J,Reed,558666300,tyler63@example.net,962 Cunningham Throughway,Taylorburgh,Kansas,47050,Monaco,181960,975267.72233.LE.604
2,3,B,Moss,3493371326,coreycarlson@example.org,21295 Michael Lock,Jasonview,Colorado,4185,Congo,13389,633312.79757.BR.660
3,4,M,Hudson,821435310,pguerrero@example.com,640 Gibson Road,Munozview,Georgia,20729,Georgia,83863,965699.98808.SL.770
4,5,J,Tran,3204000112,lmcgee@example.org,43945 Anderson Views,Mcconnelltown,Montana,77920,Guam,794026,388608.68034.SS.644
...,...,...,...,...,...,...,...,...,...,...,...,...
100,101,Barbara,Phillips,2892768306,eileen28@example.net,22867 Amanda Junction,Princetown,West Virginia,68873,Tuvalu,373467,952028.45765.ME.132
101,102,Carrie,Stone,2302183413,carriedelacruz@example.com,643 Moore Port,Johnnyton,South Carolina,51482,Cayman Islands,65627,833898.88167.SL.120
102,103,Lisa,Hahn,3090726621,mason03@example.net,6502 Katherine Estates,Robinton,North Carolina,16110,Fiji,298069,754527.98524.LE.132
103,104,Cynthia,Higgins,4154724816,njones@example.org,47238 Tristan Shore,Muellerport,Idaho,22393,Russian Federation,901627,234232.16110.SS.603
104,105,Richard,Silva,2379573264,helenpage@example.org,75015 Webster Falls,Torresview,California,52595,Gambia,204653,108907.14014.LE.119

In [14]:
# Convert dataset_2 to a csv file
import os

def save_dataframe_to_csv(df, filename='dataset_2.csv', folder='datasets'):
    """
    Save the DataFrame as a CSV file in the specified folder.

    Parameters:
    df (pd.DataFrame): The DataFrame to save.
    filename (str): The name of the CSV file. Default is 'dataset_2.csv'.
    folder (str): The folder where the file will be saved. Default is 'datasets'.

    Returns:
    str: The path to the saved file.
    """
    # Ensure the folder exists
    if not os.path.exists(folder):
        os.makedirs(folder)
    
    # Create the full file path
    file_path = os.path.join(folder, filename)
    
    # Save the DataFrame to a CSV file
    df.to_csv(file_path, index=False)
    
    return file_path

# Save the DataFrame as a CSV file
file_path = save_dataframe_to_csv(dataset_2)
print(f"DataFrame saved to: {file_path}")

DataFrame saved to: datasets\dataset_2.csv