# Sets of example fields/columns from FATCA IRS forms

In [18]:
import pandas as pd
import matplotlib.pyplot as plt
import numpy as np

Observations and notes: 
1. The header of the entities in each form differ. Example: ADV has chief_compliance_officer and 8957 has RO ( Responsible Officer). Splink requires that column headings are the same to compare. Need a way to do this without losing track of which officer we are talking about. 
2. There are multiple addresses: place of business, mailing address, address of officer. Would have to change into: address1, address2, etc. 
3. ADV form has Schedule A that you only fill out when you first register with names officers etc. so the names won't be on every annual form. They use Schedule C to update officers.

### Create sets of headings of relevant entity information from IRS forms ADV and 8957

In [12]:
# Creating a set with all the field descriptions from the SEC Form ADV document
adv_set = {
    "full_name",
    "business_name",
    "sec_file_number",
    "cik_numbers",
    "crd_number",
    "business_address_number_and_street",
    "business_address_city",
    "business_address_state",
    "business_address_country",
    "business_address_zip",
    "business_telephone",
    "fax_number",
    "business_mailing_address",
    "business_mailing_address_city",
    "business_mailing_address_state",
    "business_mailing_address_country",
    "business_mailing_address_zip",
    "chief_compliance_officer_name",
    "chief_compliance_officer_other_titles",
    "chief_compliance_officer_telephone_number",
    "chief_compliance_officer_fax_number",
    "chief_compliance_officer_address_number_and_street",
    "chief_compliance_officer_address_city",
    "chief_compliance_officer_address_state",
    "chief_compliance_officer_address_country",
    "chief_compliance_officer_address_zip",
    "chief_compliance_officer_email_address",
    "irs_employer_identification_number",
    "additional_regulatory_contact_name",
    "additional_regulatory_contact_titles",
    "additional_regulatory_contact_telephone_number",
    "additional_regulatory_contact_fax_number",
    "additional_regulatory_contact_address_number_and_street",
    "additional_regulatory_contact_address_city",
    "additional_regulatory_contact_address_state",
    "additional_regulatory_contact_address_country",
    "additional_regulatory_contact_address_zip",
    "additional_regulatory_contact_email_address",
    "registered_foreign_financial_regulatory_authority",
    "state_under_whose_laws_your_partnership_was_formed",
    "country_under_whose_laws_your_partnership_was_formed",
    "month_fiscal_year_ends",
    "1_billion_or_more_in_assets_on_the_last_day_of_your_most_recent_fiscal_year",
    "approximate_amount_of_assets",
    "legal_entity_identifier"
}

# Display the set
adv_set

{'1_billion_or_more_in_assets_on_the_last_day_of_your_most_recent_fiscal_year',
 'additional_regulatory_contact_address_city',
 'additional_regulatory_contact_address_country',
 'additional_regulatory_contact_address_number_and_street',
 'additional_regulatory_contact_address_state',
 'additional_regulatory_contact_address_zip',
 'additional_regulatory_contact_email_address',
 'additional_regulatory_contact_fax_number',
 'additional_regulatory_contact_name',
 'additional_regulatory_contact_telephone_number',
 'additional_regulatory_contact_titles',
 'approximate_amount_of_assets',
 'business_address_city',
 'business_address_country',
 'business_address_number_and_street',
 'business_address_state',
 'business_address_zip',
 'business_mailing_address',
 'business_mailing_address_city',
 'business_mailing_address_country',
 'business_mailing_address_state',
 'business_mailing_address_zip',
 'business_name',
 'business_telephone',
 'chief_compliance_officer_address_city',
 'chief_compliance_officer_address_country',
 'chief_compliance_officer_address_number_and_street',
 'chief_compliance_officer_address_state',
 'chief_compliance_officer_address_zip',
 'chief_compliance_officer_email_address',
 'chief_compliance_officer_fax_number',
 'chief_compliance_officer_name',
 'chief_compliance_officer_other_titles',
 'chief_compliance_officer_telephone_number',
 'cik_numbers',
 'country_under_whose_laws_your_partnership_was_formed',
 'crd_number',
 'fax_number',
 'full_name',
 'irs_employer_identification_number',
 'legal_entity_identifier',
 'month_fiscal_year_ends',
 'registered_foreign_financial_regulatory_authority',
 'sec_file_number',
 'state_under_whose_laws_your_partnership_was_formed'}

In [13]:
# Creating a set with all the important fields from the IRS Form 8957
f8957_set = {
    "financial_institution_type",
    "business_name",
    "business_mailing_address",
    "business_mailing_address_city",
    "business_mailing_address_state",
    "business_mailing_address_country",
    "business_mailing_address_zip",
    "country_tax_ID",
    "qi_ein",
    "wp_ein",
    "wt_ein",
    "us_ein",
    "business_title_of_ro",
    "ro_lastname",
    "ro_firstname",
    "ro_middlename",
    "ro_address_city",
    "ro_address_country",
    "ro_business_address_line1",
    "ro_business_address_line2",
    "ro_address_state",
    "ro_address_country",
    "ro_address_zip",
    "ro_business_telephone_number",
    "ro_business_fax_number",
    "ro_business_email_address",
    "po_lastname",
    "po_firstname",
    "po_middlename",
    "po_address_city",
    "po_address_country",
    "po_business_address_line1",
    "po_business_address_line2",
    "po_address_state",
    "po_address_country",
    "po_address_zip",
    "po_business_telephone_number",
    "po_business_fax_number",
    "po_business_email_address",
    "name_of_member_financial_institution",
    "country_of_member_financial_institution",
    "fi_common_parent_entity_of_expanded_affiliated_group?",
    "name_of_expanded_affiliated_groups_common_parent_entity",
    "fatca_id_of_expanded_affiliated_groups_common_parent_entity",
    "signature_name",
    "signature_date"
}

# Display the set
f8957_set

{'business_mailing_address',
 'business_mailing_address_city',
 'business_mailing_address_country',
 'business_mailing_address_state',
 'business_mailing_address_zip',
 'business_name',
 'business_title_of_ro',
 'country_of_member_financial_institution',
 'country_tax_ID',
 'fatca_id_of_expanded_affiliated_groups_common_parent_entity',
 'fi_common_parent_entity_of_expanded_affiliated_group?',
 'financial_institution_type',
 'name_of_expanded_affiliated_groups_common_parent_entity',
 'name_of_member_financial_institution',
 'po_address_city',
 'po_address_country',
 'po_address_state',
 'po_address_zip',
 'po_business_address_line1',
 'po_business_address_line2',
 'po_business_email_address',
 'po_business_fax_number',
 'po_business_telephone_number',
 'po_firstname',
 'po_lastname',
 'po_middlename',
 'qi_ein',
 'ro_address_city',
 'ro_address_country',
 'ro_address_state',
 'ro_address_zip',
 'ro_business_address_line1',
 'ro_business_address_line2',
 'ro_business_email_address',
 'ro_business_fax_number',
 'ro_business_telephone_number',
 'ro_firstname',
 'ro_lastname',
 'ro_middlename',
 'signature_date',
 'signature_name',
 'us_ein',
 'wp_ein',
 'wt_ein'}

### Find similar headings in each set

In [14]:
# Find the intersection (similarities) between the two sets
similarities = adv_set.intersection(f8957_set)

# Display the similarities
similarities

{'business_mailing_address',
 'business_mailing_address_city',
 'business_mailing_address_country',
 'business_mailing_address_state',
 'business_mailing_address_zip',
 'business_name'}

### Create dataframes of fake info for each set

In [21]:
# Create a DataFrame with the headers from adv_set
df = pd.DataFrame(columns=sorted(adv_set))
df

Empty DataFrame
Columns: [1_billion_or_more_in_assets_on_the_last_day_of_your_most_recent_fiscal_year, additional_regulatory_contact_address_city, additional_regulatory_contact_address_country, additional_regulatory_contact_address_number_and_street, additional_regulatory_contact_address_state, additional_regulatory_contact_address_zip, additional_regulatory_contact_email_address, additional_regulatory_contact_fax_number, additional_regulatory_contact_name, additional_regulatory_contact_telephone_number, additional_regulatory_contact_titles, approximate_amount_of_assets, business_address_city, business_address_country, business_address_number_and_street, business_address_state, business_address_zip, business_mailing_address, business_mailing_address_city, business_mailing_address_country, business_mailing_address_state, business_mailing_address_zip, business_name, business_telephone, chief_compliance_officer_address_city, chief_compliance_officer_address_country, chief_compliance_officer_address_number_and_street, chief_compliance_officer_address_state, chief_compliance_officer_address_zip, chief_compliance_officer_email_address, chief_compliance_officer_fax_number, chief_compliance_officer_name, chief_compliance_officer_other_titles, chief_compliance_officer_telephone_number, cik_numbers, country_under_whose_laws_your_partnership_was_formed, crd_number, fax_number, full_name, irs_employer_identification_number, legal_entity_identifier, month_fiscal_year_ends, registered_foreign_financial_regulatory_authority, sec_file_number, state_under_whose_laws_your_partnership_was_formed]
Index: []

[0 rows x 45 columns]

In [25]:
import pandas as pd

# Define the set
adv_set = {
    "full_name",
    "business_name",
    "sec_file_number",
    "cik_numbers",
    "crd_number",
    "business_address_number_and_street",
    "business_address_city",
    "business_address_state",
    "business_address_country",
    "business_address_zip",
    "business_telephone",
    "fax_number",
    "business_mailing_address",
    "business_mailing_address_city",
    "business_mailing_address_state",
    "business_mailing_address_country",
    "business_mailing_address_zip",
    "chief_compliance_officer_name",
    "chief_compliance_officer_other_titles",
    "chief_compliance_officer_telephone_number",
    "chief_compliance_officer_fax_number",
    "chief_compliance_officer_address_number_and_street",
    "chief_compliance_officer_address_city",
    "chief_compliance_officer_address_state",
    "chief_compliance_officer_address_country",
    "chief_compliance_officer_address_zip",
    "chief_compliance_officer_email_address",
    "irs_employer_identification_number",
    "additional_regulatory_contact_name",
    "additional_regulatory_contact_titles",
    "additional_regulatory_contact_telephone_number",
    "additional_regulatory_contact_fax_number",
    "additional_regulatory_contact_address_number_and_street",
    "additional_regulatory_contact_address_city",
    "additional_regulatory_contact_address_state",
    "additional_regulatory_contact_address_country",
    "additional_regulatory_contact_address_zip",
    "additional_regulatory_contact_email_address",
    "registered_foreign_financial_regulatory_authority",
    "state_under_whose_laws_your_partnership_was_formed",
    "country_under_whose_laws_your_partnership_was_formed",
    "month_fiscal_year_ends",
    "1_billion_or_more_in_assets_on_the_last_day_of_your_most_recent_fiscal_year",
    "approximate_amount_of_assets",
    "legal_entity_identifier"
}

# Create a DataFrame with the headers from adv_set
adv_df = pd.DataFrame(columns=sorted(adv_set))

# Generate fake data for each column
fake_data = {
    "full_name": ["John Doe", "Jane Smith", "Alice Johnson", "Bob Brown", "Charlie Black"],
    "business_name": ["Doe Inc.", "Smith LLC", "Johnson Ltd.", "Brown Corp.", "Black & Co."],
    "sec_file_number": ["801-12345", "801-23456", "801-34567", "801-45678", "801-56789"],
    "cik_numbers": ["000123456", "000234567", "000345678", "000456789", "000567890"],
    "crd_number": ["12345", "23456", "34567", "45678", "56789"],
    "business_address_number_and_street": ["123 Main St", "456 Elm St", "789 Oak St", "101 Pine St", "202 Maple St"],
    "business_address_city": ["Anytown", "Othertown", "Sometown", "New City", "Oldtown"],
    "business_address_state": ["NY", "CA", "TX", "FL", "IL"],
    "business_address_country": ["USA", "USA", "USA", "USA", "USA"],
    "business_address_zip": ["12345", "23456", "34567", "45678", "56789"],
    "business_telephone": ["123-456-7890", "234-567-8901", "345-678-9012", "456-789-0123", "567-890-1234"],
    "fax_number": ["123-456-7891", "234-567-8902", "345-678-9013", "456-789-0124", "567-890-1235"],
    "business_mailing_address": ["123 Main St", "456 Elm St", "789 Oak St", "101 Pine St", "202 Maple St"],
    "business_mailing_address_city": ["Anytown", "Othertown", "Sometown", "New City", "Oldtown"],
    "business_mailing_address_state": ["NY", "CA", "TX", "FL", "IL"],
    "business_mailing_address_country": ["USA", "USA", "USA", "USA", "USA"],
    "business_mailing_address_zip": ["12345", "23456", "34567", "45678", "56789"],
    "chief_compliance_officer_name": ["John Doe", "Jane Smith", "Alice Johnson", "Bob Brown", "Charlie Black"],
    "chief_compliance_officer_other_titles": ["CFO", "COO", "CTO", "CIO", "CMO"],
    "chief_compliance_officer_telephone_number": ["123-456-7890", "234-567-8901", "345-678-9012", "456-789-0123", "567-890-1234"],
    "chief_compliance_officer_fax_number": ["123-456-7891", "234-567-8902", "345-678-9013", "456-789-0124", "567-890-1235"],
    "chief_compliance_officer_address_number_and_street": ["123 Main St", "456 Elm St", "789 Oak St", "101 Pine St", "202 Maple St"],
    "chief_compliance_officer_address_city": ["Anytown", "Othertown", "Sometown", "New City", "Oldtown"],
    "chief_compliance_officer_address_state": ["NY", "CA", "TX", "FL", "IL"],
    "chief_compliance_officer_address_country": ["USA", "USA", "USA", "USA", "USA"],
    "chief_compliance_officer_address_zip": ["12345", "23456", "34567", "45678", "56789"],
    "chief_compliance_officer_email_address": ["john.doe@example.com", "jane.smith@example.com", "alice.johnson@example.com", "bob.brown@example.com", "charlie.black@example.com"],
    "irs_employer_identification_number": ["12-3456789", "23-4567890", "34-5678901", "45-6789012", "56-7890123"],
    "additional_regulatory_contact_name": ["John Doe", "Jane Smith", "Alice Johnson", "Bob Brown", "Charlie Black"],
    "additional_regulatory_contact_titles": ["CFO", "COO", "CTO", "CIO", "CMO"],
    "additional_regulatory_contact_telephone_number": ["123-456-7890", "234-567-8901", "345-678-9012", "456-789-0123", "567-890-1234"],
    "additional_regulatory_contact_fax_number": ["123-456-7891", "234-567-8902", "345-678-9013", "456-789-0124", "567-890-1235"],
    "additional_regulatory_contact_address_number_and_street": ["123 Main St", "456 Elm St", "789 Oak St", "101 Pine St", "202 Maple St"],
    "additional_regulatory_contact_address_city": ["Anytown", "Othertown", "Sometown", "New City", "Oldtown"],
    "additional_regulatory_contact_address_state": ["NY", "CA", "TX", "FL", "IL"],
    "additional_regulatory_contact_address_country": ["USA", "USA", "USA", "USA", "USA"],
    "additional_regulatory_contact_address_zip": ["12345", "23456", "34567", "45678", "56789"],
    "additional_regulatory_contact_email_address": ["john.doe@example.com", "jane.smith@example.com", "alice.johnson@example.com", "bob.brown@example.com", "charlie.black@example.com"],
    "registered_foreign_financial_regulatory_authority": ["Authority 1", "Authority 2", "Authority 3", "Authority 4", "Authority 5"],
    "state_under_whose_laws_your_partnership_was_formed": ["NY", "CA", "TX", "FL", "IL"],
    "country_under_whose_laws_your_partnership_was_formed": ["USA", "USA", "USA", "USA", "USA"],
    "month_fiscal_year_ends": ["December", "March", "June", "September", "October"],
    "1_billion_or_more_in_assets_on_the_last_day_of_your_most_recent_fiscal_year": [True, False, True, False, True],
    "approximate_amount_of_assets": ["$1 billion", "$2 billion", "$3 billion", "$4 billion", "$5 billion"],
    "legal_entity_identifier": ["LEI123456", "LEI234567", "LEI345678", "LEI456789", "LEI567890"]
}

# Add the fake data to the DataFrame
for column in adv_df.columns:
    if column in fake_data:
        adv_df[column] = fake_data[column]
    else:
        adv_df[column] = [None] * 5  # Fill with None if no fake data is provided

# Display the DataFrame
adv_df

,1_billion_or_more_in_assets_on_the_last_day_of_your_most_recent_fiscal_year,additional_regulatory_contact_address_city,additional_regulatory_contact_address_country,additional_regulatory_contact_address_number_and_street,additional_regulatory_contact_address_state,additional_regulatory_contact_address_zip,additional_regulatory_contact_email_address,additional_regulatory_contact_fax_number,additional_regulatory_contact_name,additional_regulatory_contact_telephone_number,...,country_under_whose_laws_your_partnership_was_formed,crd_number,fax_number,full_name,irs_employer_identification_number,legal_entity_identifier,month_fiscal_year_ends,registered_foreign_financial_regulatory_authority,sec_file_number,state_under_whose_laws_your_partnership_was_formed
0,True,Anytown,USA,123 Main St,NY,12345,john.doe@example.com,123-456-7891,John Doe,123-456-7890,...,USA,12345,123-456-7891,John Doe,12-3456789,LEI123456,December,Authority 1,801-12345,NY
1,False,Othertown,USA,456 Elm St,CA,23456,jane.smith@example.com,234-567-8902,Jane Smith,234-567-8901,...,USA,23456,234-567-8902,Jane Smith,23-4567890,LEI234567,March,Authority 2,801-23456,CA
2,True,Sometown,USA,789 Oak St,TX,34567,alice.johnson@example.com,345-678-9013,Alice Johnson,345-678-9012,...,USA,34567,345-678-9013,Alice Johnson,34-5678901,LEI345678,June,Authority 3,801-34567,TX
3,False,New City,USA,101 Pine St,FL,45678,bob.brown@example.com,456-789-0124,Bob Brown,456-789-0123,...,USA,45678,456-789-0124,Bob Brown,45-6789012,LEI456789,September,Authority 4,801-45678,FL
4,True,Oldtown,USA,202 Maple St,IL,56789,charlie.black@example.com,567-890-1235,Charlie Black,567-890-1234,...,USA,56789,567-890-1235,Charlie Black,56-7890123,LEI567890,October,Authority 5,801-56789,IL

In [26]:
# Drop 1_billion...column, too long
# Delete the specified column
adv_df.drop(columns=["1_billion_or_more_in_assets_on_the_last_day_of_your_most_recent_fiscal_year"], inplace=True)

# Display the DataFrame
adv_df

,additional_regulatory_contact_address_city,additional_regulatory_contact_address_country,additional_regulatory_contact_address_number_and_street,additional_regulatory_contact_address_state,additional_regulatory_contact_address_zip,additional_regulatory_contact_email_address,additional_regulatory_contact_fax_number,additional_regulatory_contact_name,additional_regulatory_contact_telephone_number,additional_regulatory_contact_titles,...,country_under_whose_laws_your_partnership_was_formed,crd_number,fax_number,full_name,irs_employer_identification_number,legal_entity_identifier,month_fiscal_year_ends,registered_foreign_financial_regulatory_authority,sec_file_number,state_under_whose_laws_your_partnership_was_formed
0,Anytown,USA,123 Main St,NY,12345,john.doe@example.com,123-456-7891,John Doe,123-456-7890,CFO,...,USA,12345,123-456-7891,John Doe,12-3456789,LEI123456,December,Authority 1,801-12345,NY
1,Othertown,USA,456 Elm St,CA,23456,jane.smith@example.com,234-567-8902,Jane Smith,234-567-8901,COO,...,USA,23456,234-567-8902,Jane Smith,23-4567890,LEI234567,March,Authority 2,801-23456,CA
2,Sometown,USA,789 Oak St,TX,34567,alice.johnson@example.com,345-678-9013,Alice Johnson,345-678-9012,CTO,...,USA,34567,345-678-9013,Alice Johnson,34-5678901,LEI345678,June,Authority 3,801-34567,TX
3,New City,USA,101 Pine St,FL,45678,bob.brown@example.com,456-789-0124,Bob Brown,456-789-0123,CIO,...,USA,45678,456-789-0124,Bob Brown,45-6789012,LEI456789,September,Authority 4,801-45678,FL
4,Oldtown,USA,202 Maple St,IL,56789,charlie.black@example.com,567-890-1235,Charlie Black,567-890-1234,CMO,...,USA,56789,567-890-1235,Charlie Black,56-7890123,LEI567890,October,Authority 5,801-56789,IL

In [27]:
# Create a csv file from adv_df
import pandas as pd

# Assuming adv_df is your DataFrame
adv_df.to_csv('adv.csv', index=False)

In [29]:
!python --version

Python 3.12.4

In [31]:
pip install faker

Defaulting to user installation because normal site-packages is not writeable
Collecting faker
  Downloading Faker-33.3.0-py3-none-any.whl.metadata (15 kB)
Requirement already satisfied: python-dateutil>=2.4 in c:\tools\anaconda3\lib\site-packages (from faker) (2.9.0.post0)
Requirement already satisfied: typing-extensions in c:\tools\anaconda3\lib\site-packages (from faker) (4.11.0)
Requirement already satisfied: six>=1.5 in c:\tools\anaconda3\lib\site-packages (from python-dateutil>=2.4->faker) (1.16.0)
Downloading Faker-33.3.0-py3-none-any.whl (1.9 MB)
   ---------------------------------------- 0.0/1.9 MB ? eta -:--:--
    --------------------------------------- 0.0/1.9 MB 1.3 MB/s eta 0:00:02
   ------ --------------------------------- 0.3/1.9 MB 4.1 MB/s eta 0:00:01
   ----------------------------- ---------- 1.4/1.9 MB 12.8 MB/s eta 0:00:01
   ---------------------------------------- 1.9/1.9 MB 13.4 MB/s eta 0:00:00
Installing collected packages: faker
Successfully installed faker-33.3.0
Note: you may need to restart the kernel to use updated packages.

  WARNING: The script faker.exe is installed in 'C:\Users\Amanda.Rodgers\AppData\Roaming\Python\Python312\Scripts' which is not on PATH.
  Consider adding this directory to PATH or, if you prefer to suppress this warning, use --no-warn-script-location.

### Create data frame from f8957_set

In [34]:
import pandas as pd
from faker import Faker

# Initialize Faker
fake = Faker()

# Define the headers
headers = [
    "financial_institution_type",
    "business_name",
    "business_mailing_address",
    "business_mailing_address_city",
    "business_mailing_address_state",
    "business_mailing_address_country",
    "business_mailing_address_zip",
    "country_tax_ID",
    "qi_ein",
    "wp_ein",
    "wt_ein",
    "us_ein",
    "business_title_of_ro",
    "ro_lastname",
    "ro_firstname",
    "ro_middlename",
    "ro_address_city",
    "ro_address_country",
    "ro_business_address_line1",
    "ro_business_address_line2",
    "ro_address_state",
    "ro_address_zip",
    "ro_business_telephone_number",
    "ro_business_fax_number",
    "ro_business_email_address",
    "po_lastname",
    "po_firstname",
    "po_middlename",
    "po_address_city",
    "po_address_country",
    "po_business_address_line1",
    "po_business_address_line2",
    "po_address_state",
    "po_address_zip",
    "po_business_telephone_number",
    "po_business_fax_number",
    "po_business_email_address",
    "name_of_member_financial_institution",
    "country_of_member_financial_institution",
    "fi_common_parent_entity_of_expanded_affiliated_group?",
    "name_of_expanded_affiliated_groups_common_parent_entity",
    "fatca_id_of_expanded_affiliated_groups_common_parent_entity",
    "signature_name",
    "signature_date"
]

# Generate fake data for five rows
data = []
for _ in range(5):
    row = [
        fake.company_suffix(),  # financial_institution_type
        fake.company(),  # business_name
        fake.address(),  # business_mailing_address
        fake.city(),  # business_mailing_address_city
        fake.state_abbr(),  # business_mailing_address_state
        fake.country(),  # business_mailing_address_country
        fake.zipcode(),  # business_mailing_address_zip
        fake.uuid4(),  # country_tax_ID
        fake.ein(),  # qi_ein
        fake.ein(),  # wp_ein
        fake.ein(),  # wt_ein
        fake.ein(),  # us_ein
        fake.job(),  # business_title_of_ro
        fake.last_name(),  # ro_lastname
        fake.first_name(),  # ro_firstname
        fake.first_name(),  # ro_middlename
        fake.city(),  # ro_address_city
        fake.country(),  # ro_address_country
        fake.street_address(),  # ro_business_address_line1
        fake.secondary_address(),  # ro_business_address_line2
        fake.state_abbr(),  # ro_address_state
        fake.zipcode(),  # ro_address_zip
        fake.phone_number(),  # ro_business_telephone_number
        fake.phone_number(),  # ro_business_fax_number
        fake.email(),  # ro_business_email_address
        fake.last_name(),  # po_lastname
        fake.first_name(),  # po_firstname
        fake.first_name(),  # po_middlename
        fake.city(),  # po_address_city
        fake.country(),  # po_address_country
        fake.street_address(),  # po_business_address_line1
        fake.secondary_address(),  # po_business_address_line2
        fake.state_abbr(),  # po_address_state
        fake.zipcode(),  # po_address_zip
        fake.phone_number(),  # po_business_telephone_number
        fake.phone_number(),  # po_business_fax_number
        fake.email(),  # po_business_email_address
        fake.company(),  # name_of_member_financial_institution
        fake.country(),  # country_of_member_financial_institution
        fake.boolean(),  # fi_common_parent_entity_of_expanded_affiliated_group?
        fake.company(),  # name_of_expanded_affiliated_groups_common_parent_entity
        fake.uuid4(),  # fatca_id_of_expanded_affiliated_groups_common_parent_entity
        fake.name(),  # signature_name
        fake.date()  # signature_date
    ]
    data.append(row)

# Create DataFrame
f8957_df = pd.DataFrame(data, columns=headers)

# Display the DataFrame
print(df)

  financial_institution_type                   business_name  \
0                        Inc                   Sanchez-Lopez
1                        LLC                  Williams-Jones
2                        PLC                   Henry-Carroll
3                        Ltd                      Walker Ltd
4                        Ltd  Bailey, Williams and Carpenter

    business_mailing_address business_mailing_address_city  \
0  828 Smith Locks Suite 538                    West Jerry
1         4539 Dustin Summit                  Lake Natasha
2       4656 Fritz Junctions                     Daleburgh
3           5488 Ortiz Brook                    North Anna
4         Unit 3846 Box 8934                    Dianeburgh

  business_mailing_address_state business_mailing_address_country  \
0                             ID                         Colombia
1                             VI                            Qatar
2                             MT                          Estonia
3                             VI                            Congo
4                             VA                          Ireland

  business_mailing_address_zip                        country_tax_ID  \
0                        06551  a3f44662-92e6-4070-a5f8-00ca88430e53
1                        13581  d7cbb7f0-082a-4d1f-a42b-cb8fb309dad0
2                        61736  07ff6813-3de0-4899-b391-2d6dc8b738a2
3                        61734  e8004f5e-ac94-4a2f-ba5d-eda4e9db89e0
4                        72563  3f3aa83b-860c-4e45-9b1d-9ad35ce4bfb9

       qi_ein      wp_ein  ... po_business_telephone_number  \
0  11-2932467  88-1291960  ...          (610)663-5869x14558
1  53-7182051  56-2886396  ...             001-657-867-4800
2  12-2997911  40-5016286  ...           887-460-9000x61547
3  77-5036209  54-7220245  ...          (388)829-8805x79181
4  81-0842151  84-4968589  ...                   2507048639

  po_business_fax_number     po_business_email_address  \
0    (244)539-3484x79699   johnsonjermaine@example.org
1        +1-450-641-6576        margaret96@example.com
2        +1-931-271-5755         crystal14@example.org
3             5905153393   alexanderlawson@example.org
4      (601)466-1291x768  brittanyfaulkner@example.net

  name_of_member_financial_institution  \
0                            Lee-Green
1                         Bautista LLC
2                        Mccormick PLC
3                        Walker-Morgan
4                       Francis-Garcia

  country_of_member_financial_institution  \
0                                    Iran
1                             Timor-Leste
2                                   Chile
3                        Saint Barthelemy
4                                    Fiji

  fi_common_parent_entity_of_expanded_affiliated_group?  \
0                                              False
1                                               True
2                                               True
3                                               True
4                                               True

  name_of_expanded_affiliated_groups_common_parent_entity  \
0                                          Evans Ltd
1                                         Barnes Inc
2                                   Carroll-Gonzales
3                           Jackson, Haley and Silva
4                                       Harris Group

  fatca_id_of_expanded_affiliated_groups_common_parent_entity  \
0               18789b67-c5a9-4175-8605-a2d9028ed516
1               c7aa0101-ace4-491e-9803-e8739453326e
2               53ae82e2-b307-4fd0-9091-39b442a539ae
3               9f82f63f-e492-47de-bcb2-638b9e79ab32
4               42593fb7-df83-4e62-b884-6fc75fc939f7

    signature_name signature_date
0     Brian Hughes     1989-10-28
1  Valerie Oconnor     1997-11-16
2       Luke Myers     2021-11-25
3    Jessica Cross     2012-03-19
4       Paul Ramos     1994-10-06

[5 rows x 44 columns]

In [35]:
f8957_df

,financial_institution_type,business_name,business_mailing_address,business_mailing_address_city,business_mailing_address_state,business_mailing_address_country,business_mailing_address_zip,country_tax_ID,qi_ein,wp_ein,...,po_business_telephone_number,po_business_fax_number,po_business_email_address,name_of_member_financial_institution,country_of_member_financial_institution,fi_common_parent_entity_of_expanded_affiliated_group?,name_of_expanded_affiliated_groups_common_parent_entity,fatca_id_of_expanded_affiliated_groups_common_parent_entity,signature_name,signature_date
0,Ltd,Dorsey LLC,"224 Richard Summit\nLake Patricia, LA 35878",South Laurenmouth,AL,Falkland Islands (Malvinas),73797,7566bf69-5f53-48ef-a117-e99c822c3e5e,73-6089839,06-6381609,...,001-980-802-5889x04584,001-977-813-9928x595,adam07@example.net,"Solis, Rice and Powell",Vietnam,False,King-Carney,d52c25db-661b-4fbc-9a09-3f1727162477,John Bullock,2000-02-04
1,and Sons,Reynolds-Adams,USS Griffin\nFPO AP 24773,West Richard,DE,Samoa,63051,f8c7d3cf-6e2a-46c7-889b-2373e7c4c865,01-9359913,48-4170219,...,(852)228-8847x625,001-944-794-9119x064,daviskevin@example.com,Murphy-Reyes,Cayman Islands,False,"Clark, Crosby and Brown",0241e4e5-3750-4dda-90f1-53feacb98f31,Nina Berger,1985-03-24
2,PLC,"Lawrence, Davis and Nixon","PSC 5705, Box 6949\nAPO AP 43650",Port Bailey,CO,Pitcairn Islands,43202,d264545e-d3b8-4908-af10-c194a23bcf09,64-5629533,63-8882702,...,578-675-9879x7271,+1-776-297-0140,gramirez@example.com,Fisher-Aguilar,Albania,True,Martinez Group,9a6abe4f-dfa1-40f5-a2d9-1f7acb90b649,Amanda Davis,1992-09-08
3,Inc,Mccann Group,"88318 Bennett Mall\nVeronicamouth, SD 65378",New Justin,ME,Moldova,81059,2efb97bb-0201-43c4-a8f9-60f0e4bcdcdd,83-2594745,13-5323155,...,(273)246-8370,001-496-823-5292x7963,maureen15@example.net,"Soto, Kim and Chen",Guinea-Bissau,True,Pham Group,49da031c-1600-48c7-a271-d88dd55ea7d3,Dan Morgan,1977-03-07
4,Ltd,"Stevens, Mason and King","13224 Taylor Ramp Suite 051\nWest Haleyport, W...",Dianeshire,WI,Reunion,09855,6f391da3-3dba-4f9e-bf22-4bfdd21bdc14,93-6710664,13-5430108,...,(485)723-9022x8306,500.317.0765x6862,waltergarcia@example.net,Ray Inc,Indonesia,False,Wood-Reynolds,d41b7e56-02ff-4dbd-a8d7-875af47366d8,Marcus Dawson,1993-04-07

### Clean datasets per Splink's data prep prerequisites

In [4]:
# TO DO: 
# 1. Add a unique_id column (default for Splink) as primary key
# 2. Conformant datasets: same column names and data format and data types.
# 3. Make sure nulls are true nulls and not empty strings. 
# 4. Remove Mr or Ms or Mrs in first name column. 
# 5. Trim leading and trailing whitespace from strings values
# 6. Remove special characters. Ex. O'Hara should be Ohara
# 7. Standardize date formats into a string in this format: "yyyy-mm-dd"
# 8. Replace abbreviations with full words. Ex. standarize "St." to "Street"

In [7]:
# Function to extract street number and name for business_mailing_address column
def extract_number_and_street(full_address):
    """
    This function takes a full address and extracts the number and street name.
    """
    # Split the address by newline character
    address_parts = full_address.split('\n')
    
    # The first part contains the number and street name
    number_and_street = address_parts[0]
    
    return number_and_street

In [36]:
# Apply the function to the column
f8957_df['business_mailing_address'] = f8957_df['business_mailing_address'].apply(extract_number_and_street)

In [13]:
f8957_df

,financial_institution_type,business_name,business_mailing_address,business_mailing_address_city,business_mailing_address_state,business_mailing_address_country,business_mailing_address_zip,country_tax_ID,qi_ein,wp_ein,...,po_business_telephone_number,po_business_fax_number,po_business_email_address,name_of_member_financial_institution,country_of_member_financial_institution,fi_common_parent_entity_of_expanded_affiliated_group?,name_of_expanded_affiliated_groups_common_parent_entity,fatca_id_of_expanded_affiliated_groups_common_parent_entity,signature_name,signature_date
0,and Sons,Odom-Hamilton,477 Carter Crossroad,South Nancy,MI,Saudi Arabia,94460,a902dac3-2fbd-4f16-b416-df730739c743,22-9707061,32-0139353,...,001-272-857-8959x89472,+1-890-945-0634,crystalortiz@example.com,"Rogers, Garcia and Montgomery",Pitcairn Islands,True,Williams PLC,bc9cfbc3-e104-47d4-b84f-e4dd3a250d9d,Vicki Simmons,1978-10-23
1,Group,Harris-Johnson,5898 Blake Course,Petersenberg,CT,Guyana,28432,438efcb1-c2bd-4d64-89dd-967e6e096b12,20-3967468,45-3099092,...,(524)222-0759x8362,692.476.8540x906,burchnathan@example.org,"House, Rogers and Brewer",Svalbard & Jan Mayen Islands,False,"Glover, Miller and Richard",5266026d-ddaf-486f-b865-a0cb665403b5,Elizabeth Huff,1999-01-18
2,LLC,Sanders-Martin,202 Schmidt Groves Suite 123,Bennettshire,MS,Guernsey,02508,6d595727-4a15-4ce3-b59e-26ec1f816558,75-8122351,54-5993134,...,4597869293,+1-943-504-8295x74610,davidallen@example.com,Ward Group,French Southern Territories,False,"Lawson, Ortega and Carter",863e1e9e-7974-46ab-9f27-6e691f2a5642,Mr. James Jones,1988-01-22
3,and Sons,Ferguson Group,9612 Lopez Throughway Apt. 377,Poolehaven,GA,Uzbekistan,42017,6392ec59-940b-486b-be7a-f610f242f72b,86-0069519,95-1156843,...,942.792.1013x13042,251.366.0222,forderic@example.com,Grant-Lowe,Chile,False,Carr-Short,22be6c38-8d8e-4871-9967-bb94746c8942,Andrew Lewis,1987-11-21
4,Ltd,"Reyes, Delgado and Green",9194 Jennifer Lane,West Judithfurt,ME,El Salvador,97646,7b52aadf-3d0d-4471-8cc8-8adc58471339,83-7181770,26-9400499,...,001-577-538-1135x80800,(453)326-7714x57914,gbailey@example.org,"Sims, Barnes and Lee",Eritrea,False,"Crawford, Stevenson and Ward",bc649596-3c66-4f0f-9f8a-432b9d138b87,Brandi Bowen,1996-03-10

In [37]:
# Function to remove periods from an address
def remove_periods(address):
    """
    This function removes periods from the address.
    """
    return address.replace('.', '')

In [38]:
# Apply the function to remove periods from business_mailing_address column
f8957_df['business_mailing_address'] = f8957_df['business_mailing_address'].apply(remove_periods)

In [39]:
f8957_df

,financial_institution_type,business_name,business_mailing_address,business_mailing_address_city,business_mailing_address_state,business_mailing_address_country,business_mailing_address_zip,country_tax_ID,qi_ein,wp_ein,...,po_business_telephone_number,po_business_fax_number,po_business_email_address,name_of_member_financial_institution,country_of_member_financial_institution,fi_common_parent_entity_of_expanded_affiliated_group?,name_of_expanded_affiliated_groups_common_parent_entity,fatca_id_of_expanded_affiliated_groups_common_parent_entity,signature_name,signature_date
0,Ltd,Dorsey LLC,224 Richard Summit,South Laurenmouth,AL,Falkland Islands (Malvinas),73797,7566bf69-5f53-48ef-a117-e99c822c3e5e,73-6089839,06-6381609,...,001-980-802-5889x04584,001-977-813-9928x595,adam07@example.net,"Solis, Rice and Powell",Vietnam,False,King-Carney,d52c25db-661b-4fbc-9a09-3f1727162477,John Bullock,2000-02-04
1,and Sons,Reynolds-Adams,USS Griffin,West Richard,DE,Samoa,63051,f8c7d3cf-6e2a-46c7-889b-2373e7c4c865,01-9359913,48-4170219,...,(852)228-8847x625,001-944-794-9119x064,daviskevin@example.com,Murphy-Reyes,Cayman Islands,False,"Clark, Crosby and Brown",0241e4e5-3750-4dda-90f1-53feacb98f31,Nina Berger,1985-03-24
2,PLC,"Lawrence, Davis and Nixon","PSC 5705, Box 6949",Port Bailey,CO,Pitcairn Islands,43202,d264545e-d3b8-4908-af10-c194a23bcf09,64-5629533,63-8882702,...,578-675-9879x7271,+1-776-297-0140,gramirez@example.com,Fisher-Aguilar,Albania,True,Martinez Group,9a6abe4f-dfa1-40f5-a2d9-1f7acb90b649,Amanda Davis,1992-09-08
3,Inc,Mccann Group,88318 Bennett Mall,New Justin,ME,Moldova,81059,2efb97bb-0201-43c4-a8f9-60f0e4bcdcdd,83-2594745,13-5323155,...,(273)246-8370,001-496-823-5292x7963,maureen15@example.net,"Soto, Kim and Chen",Guinea-Bissau,True,Pham Group,49da031c-1600-48c7-a271-d88dd55ea7d3,Dan Morgan,1977-03-07
4,Ltd,"Stevens, Mason and King",13224 Taylor Ramp Suite 051,Dianeshire,WI,Reunion,09855,6f391da3-3dba-4f9e-bf22-4bfdd21bdc14,93-6710664,13-5430108,...,(485)723-9022x8306,500.317.0765x6862,waltergarcia@example.net,Ray Inc,Indonesia,False,Wood-Reynolds,d41b7e56-02ff-4dbd-a8d7-875af47366d8,Marcus Dawson,1993-04-07

In [40]:
# Function to replace abbreviations with full words per Slink data prep requirements
def replace_abbreviations(address):
    """
    This function replaces common abbreviations in the address.
    """
    abbreviations = {
        'Apt': 'Apartment',
        'St': 'Street',
        'Ave': 'Avenue',
        'Rd': 'Road',
        'Blvd': 'Boulevard',
        'Dr': 'Drive',
        'Ln': 'Lane',
        'Ct': 'Court',
        'Pl': 'Place',
        'Sq': 'Square',
        'Terr': 'Terrace',
        'Pkwy': 'Parkway',
        'Cir': 'Circle'
    }
    
    for abbr, full in abbreviations.items():
        address = address.replace(abbr, full)
    
    return address

In [41]:
# Apply the function to replace abbreviations in business_mailing_address column
f8957_df['business_mailing_address'] = f8957_df['business_mailing_address'].apply(replace_abbreviations)

In [42]:
f8957_df

,financial_institution_type,business_name,business_mailing_address,business_mailing_address_city,business_mailing_address_state,business_mailing_address_country,business_mailing_address_zip,country_tax_ID,qi_ein,wp_ein,...,po_business_telephone_number,po_business_fax_number,po_business_email_address,name_of_member_financial_institution,country_of_member_financial_institution,fi_common_parent_entity_of_expanded_affiliated_group?,name_of_expanded_affiliated_groups_common_parent_entity,fatca_id_of_expanded_affiliated_groups_common_parent_entity,signature_name,signature_date
0,Ltd,Dorsey LLC,224 Richard Summit,South Laurenmouth,AL,Falkland Islands (Malvinas),73797,7566bf69-5f53-48ef-a117-e99c822c3e5e,73-6089839,06-6381609,...,001-980-802-5889x04584,001-977-813-9928x595,adam07@example.net,"Solis, Rice and Powell",Vietnam,False,King-Carney,d52c25db-661b-4fbc-9a09-3f1727162477,John Bullock,2000-02-04
1,and Sons,Reynolds-Adams,USS Griffin,West Richard,DE,Samoa,63051,f8c7d3cf-6e2a-46c7-889b-2373e7c4c865,01-9359913,48-4170219,...,(852)228-8847x625,001-944-794-9119x064,daviskevin@example.com,Murphy-Reyes,Cayman Islands,False,"Clark, Crosby and Brown",0241e4e5-3750-4dda-90f1-53feacb98f31,Nina Berger,1985-03-24
2,PLC,"Lawrence, Davis and Nixon","PSC 5705, Box 6949",Port Bailey,CO,Pitcairn Islands,43202,d264545e-d3b8-4908-af10-c194a23bcf09,64-5629533,63-8882702,...,578-675-9879x7271,+1-776-297-0140,gramirez@example.com,Fisher-Aguilar,Albania,True,Martinez Group,9a6abe4f-dfa1-40f5-a2d9-1f7acb90b649,Amanda Davis,1992-09-08
3,Inc,Mccann Group,88318 Bennett Mall,New Justin,ME,Moldova,81059,2efb97bb-0201-43c4-a8f9-60f0e4bcdcdd,83-2594745,13-5323155,...,(273)246-8370,001-496-823-5292x7963,maureen15@example.net,"Soto, Kim and Chen",Guinea-Bissau,True,Pham Group,49da031c-1600-48c7-a271-d88dd55ea7d3,Dan Morgan,1977-03-07
4,Ltd,"Stevens, Mason and King",13224 Taylor Ramp Suite 051,Dianeshire,WI,Reunion,09855,6f391da3-3dba-4f9e-bf22-4bfdd21bdc14,93-6710664,13-5430108,...,(485)723-9022x8306,500.317.0765x6862,waltergarcia@example.net,Ray Inc,Indonesia,False,Wood-Reynolds,d41b7e56-02ff-4dbd-a8d7-875af47366d8,Marcus Dawson,1993-04-07

In [26]:
# Function to remove special characters from a string replace with a space# Issue, this works independently but when applyed to df Odom-Hamilton becomes OdomHamilton
# import re

# def replace_special_characters_with_space(text):
#     """
#     This function replaces all special characters in the input string with a space.
#     """
#     return re.sub(r'[^A-Za-z0-9\s]', ' ', text)

In [29]:
# text = "Harris-Johnson"
# print (replace_special_characters_with_space(text))

Harris Johnson

In [43]:
f8957_df

,financial_institution_type,business_name,business_mailing_address,business_mailing_address_city,business_mailing_address_state,business_mailing_address_country,business_mailing_address_zip,country_tax_ID,qi_ein,wp_ein,...,po_business_telephone_number,po_business_fax_number,po_business_email_address,name_of_member_financial_institution,country_of_member_financial_institution,fi_common_parent_entity_of_expanded_affiliated_group?,name_of_expanded_affiliated_groups_common_parent_entity,fatca_id_of_expanded_affiliated_groups_common_parent_entity,signature_name,signature_date
0,Ltd,Dorsey LLC,224 Richard Summit,South Laurenmouth,AL,Falkland Islands (Malvinas),73797,7566bf69-5f53-48ef-a117-e99c822c3e5e,73-6089839,06-6381609,...,001-980-802-5889x04584,001-977-813-9928x595,adam07@example.net,"Solis, Rice and Powell",Vietnam,False,King-Carney,d52c25db-661b-4fbc-9a09-3f1727162477,John Bullock,2000-02-04
1,and Sons,Reynolds-Adams,USS Griffin,West Richard,DE,Samoa,63051,f8c7d3cf-6e2a-46c7-889b-2373e7c4c865,01-9359913,48-4170219,...,(852)228-8847x625,001-944-794-9119x064,daviskevin@example.com,Murphy-Reyes,Cayman Islands,False,"Clark, Crosby and Brown",0241e4e5-3750-4dda-90f1-53feacb98f31,Nina Berger,1985-03-24
2,PLC,"Lawrence, Davis and Nixon","PSC 5705, Box 6949",Port Bailey,CO,Pitcairn Islands,43202,d264545e-d3b8-4908-af10-c194a23bcf09,64-5629533,63-8882702,...,578-675-9879x7271,+1-776-297-0140,gramirez@example.com,Fisher-Aguilar,Albania,True,Martinez Group,9a6abe4f-dfa1-40f5-a2d9-1f7acb90b649,Amanda Davis,1992-09-08
3,Inc,Mccann Group,88318 Bennett Mall,New Justin,ME,Moldova,81059,2efb97bb-0201-43c4-a8f9-60f0e4bcdcdd,83-2594745,13-5323155,...,(273)246-8370,001-496-823-5292x7963,maureen15@example.net,"Soto, Kim and Chen",Guinea-Bissau,True,Pham Group,49da031c-1600-48c7-a271-d88dd55ea7d3,Dan Morgan,1977-03-07
4,Ltd,"Stevens, Mason and King",13224 Taylor Ramp Suite 051,Dianeshire,WI,Reunion,09855,6f391da3-3dba-4f9e-bf22-4bfdd21bdc14,93-6710664,13-5430108,...,(485)723-9022x8306,500.317.0765x6862,waltergarcia@example.net,Ray Inc,Indonesia,False,Wood-Reynolds,d41b7e56-02ff-4dbd-a8d7-875af47366d8,Marcus Dawson,1993-04-07

In [44]:
# Function to remove special characters from a string replace with a space# Issue, this works independently but when applyed to df Odom-Hamilton becomes OdomHamilton
import re

def replace_special_characters_with_space(text):
    """
    This function replaces all special characters in the input string with a space.
    """
    return re.sub(r'[^A-Za-z0-9\s]', ' ', text)

In [45]:
# Remove special characters in business_mailing_address column
# Apply the function to replace abbreviations in business_mailing_address column
f8957_df['business_mailing_address'] = f8957_df['business_mailing_address'].apply(replace_special_characters_with_space)

In [50]:
f8957_df

,financial_institution_type,business_name,business_mailing_address,business_mailing_address_city,business_mailing_address_state,business_mailing_address_country,business_mailing_address_zip,country_tax_ID,qi_ein,wp_ein,...,po_business_fax_number,po_business_email_address,name_of_member_financial_institution,country_of_member_financial_institution,fi_common_parent_entity_of_expanded_affiliated_group?,name_of_expanded_affiliated_groups_common_parent_entity,fatca_id_of_expanded_affiliated_groups_common_parent_entity,signature_name,signature_date,unique_id
0,Ltd,Dorsey LLC,224 Richard Summit,South Laurenmouth,AL,Falkland Islands (Malvinas),73797,7566bf69-5f53-48ef-a117-e99c822c3e5e,73-6089839,06-6381609,...,001-977-813-9928x595,adam07@example.net,"Solis, Rice and Powell",Vietnam,False,King-Carney,d52c25db-661b-4fbc-9a09-3f1727162477,John Bullock,2000-02-04,1
1,and Sons,Reynolds-Adams,USS Griffin,West Richard,DE,Samoa,63051,f8c7d3cf-6e2a-46c7-889b-2373e7c4c865,01-9359913,48-4170219,...,001-944-794-9119x064,daviskevin@example.com,Murphy-Reyes,Cayman Islands,False,"Clark, Crosby and Brown",0241e4e5-3750-4dda-90f1-53feacb98f31,Nina Berger,1985-03-24,2
2,PLC,"Lawrence, Davis and Nixon",PSC 5705 Box 6949,Port Bailey,CO,Pitcairn Islands,43202,d264545e-d3b8-4908-af10-c194a23bcf09,64-5629533,63-8882702,...,+1-776-297-0140,gramirez@example.com,Fisher-Aguilar,Albania,True,Martinez Group,9a6abe4f-dfa1-40f5-a2d9-1f7acb90b649,Amanda Davis,1992-09-08,3
3,Inc,Mccann Group,88318 Bennett Mall,New Justin,ME,Moldova,81059,2efb97bb-0201-43c4-a8f9-60f0e4bcdcdd,83-2594745,13-5323155,...,001-496-823-5292x7963,maureen15@example.net,"Soto, Kim and Chen",Guinea-Bissau,True,Pham Group,49da031c-1600-48c7-a271-d88dd55ea7d3,Dan Morgan,1977-03-07,4
4,Ltd,"Stevens, Mason and King",13224 Taylor Ramp Suite 051,Dianeshire,WI,Reunion,09855,6f391da3-3dba-4f9e-bf22-4bfdd21bdc14,93-6710664,13-5430108,...,500.317.0765x6862,waltergarcia@example.net,Ray Inc,Indonesia,False,Wood-Reynolds,d41b7e56-02ff-4dbd-a8d7-875af47366d8,Marcus Dawson,1993-04-07,5

In [51]:
# Move the unique_id column to the beginning
cols = ['unique_id'] + [col for col in f8957_df if col != 'unique_id']
f8957_df = f8957_df[cols]
f8957_df

,unique_id,financial_institution_type,business_name,business_mailing_address,business_mailing_address_city,business_mailing_address_state,business_mailing_address_country,business_mailing_address_zip,country_tax_ID,qi_ein,...,po_business_telephone_number,po_business_fax_number,po_business_email_address,name_of_member_financial_institution,country_of_member_financial_institution,fi_common_parent_entity_of_expanded_affiliated_group?,name_of_expanded_affiliated_groups_common_parent_entity,fatca_id_of_expanded_affiliated_groups_common_parent_entity,signature_name,signature_date
0,1,Ltd,Dorsey LLC,224 Richard Summit,South Laurenmouth,AL,Falkland Islands (Malvinas),73797,7566bf69-5f53-48ef-a117-e99c822c3e5e,73-6089839,...,001-980-802-5889x04584,001-977-813-9928x595,adam07@example.net,"Solis, Rice and Powell",Vietnam,False,King-Carney,d52c25db-661b-4fbc-9a09-3f1727162477,John Bullock,2000-02-04
1,2,and Sons,Reynolds-Adams,USS Griffin,West Richard,DE,Samoa,63051,f8c7d3cf-6e2a-46c7-889b-2373e7c4c865,01-9359913,...,(852)228-8847x625,001-944-794-9119x064,daviskevin@example.com,Murphy-Reyes,Cayman Islands,False,"Clark, Crosby and Brown",0241e4e5-3750-4dda-90f1-53feacb98f31,Nina Berger,1985-03-24
2,3,PLC,"Lawrence, Davis and Nixon",PSC 5705 Box 6949,Port Bailey,CO,Pitcairn Islands,43202,d264545e-d3b8-4908-af10-c194a23bcf09,64-5629533,...,578-675-9879x7271,+1-776-297-0140,gramirez@example.com,Fisher-Aguilar,Albania,True,Martinez Group,9a6abe4f-dfa1-40f5-a2d9-1f7acb90b649,Amanda Davis,1992-09-08
3,4,Inc,Mccann Group,88318 Bennett Mall,New Justin,ME,Moldova,81059,2efb97bb-0201-43c4-a8f9-60f0e4bcdcdd,83-2594745,...,(273)246-8370,001-496-823-5292x7963,maureen15@example.net,"Soto, Kim and Chen",Guinea-Bissau,True,Pham Group,49da031c-1600-48c7-a271-d88dd55ea7d3,Dan Morgan,1977-03-07
4,5,Ltd,"Stevens, Mason and King",13224 Taylor Ramp Suite 051,Dianeshire,WI,Reunion,09855,6f391da3-3dba-4f9e-bf22-4bfdd21bdc14,93-6710664,...,(485)723-9022x8306,500.317.0765x6862,waltergarcia@example.net,Ray Inc,Indonesia,False,Wood-Reynolds,d41b7e56-02ff-4dbd-a8d7-875af47366d8,Marcus Dawson,1993-04-07

In [52]:
# Define the function to remove special characters
def remove_special_characters(text):
    """
    This function removes all special characters from the input string.
    """
    return re.sub(r'[^A-Za-z0-9\s]', '', text)

In [55]:
# Apply the function to multiple columns
columns_to_clean = ['business_mailing_address_country']
for col in columns_to_clean:
    f8957_df[col] = f8957_df[col].apply(remove_special_characters)

In [56]:
f8957_df

,unique_id,financial_institution_type,business_name,business_mailing_address,business_mailing_address_city,business_mailing_address_state,business_mailing_address_country,business_mailing_address_zip,country_tax_ID,qi_ein,...,po_business_telephone_number,po_business_fax_number,po_business_email_address,name_of_member_financial_institution,country_of_member_financial_institution,fi_common_parent_entity_of_expanded_affiliated_group?,name_of_expanded_affiliated_groups_common_parent_entity,fatca_id_of_expanded_affiliated_groups_common_parent_entity,signature_name,signature_date
0,1,Ltd,Dorsey LLC,224 Richard Summit,South Laurenmouth,AL,Falkland Islands Malvinas,73797,7566bf69-5f53-48ef-a117-e99c822c3e5e,73-6089839,...,001-980-802-5889x04584,001-977-813-9928x595,adam07@example.net,"Solis, Rice and Powell",Vietnam,False,King-Carney,d52c25db-661b-4fbc-9a09-3f1727162477,John Bullock,2000-02-04
1,2,and Sons,Reynolds-Adams,USS Griffin,West Richard,DE,Samoa,63051,f8c7d3cf-6e2a-46c7-889b-2373e7c4c865,01-9359913,...,(852)228-8847x625,001-944-794-9119x064,daviskevin@example.com,Murphy-Reyes,Cayman Islands,False,"Clark, Crosby and Brown",0241e4e5-3750-4dda-90f1-53feacb98f31,Nina Berger,1985-03-24
2,3,PLC,"Lawrence, Davis and Nixon",PSC 5705 Box 6949,Port Bailey,CO,Pitcairn Islands,43202,d264545e-d3b8-4908-af10-c194a23bcf09,64-5629533,...,578-675-9879x7271,+1-776-297-0140,gramirez@example.com,Fisher-Aguilar,Albania,True,Martinez Group,9a6abe4f-dfa1-40f5-a2d9-1f7acb90b649,Amanda Davis,1992-09-08
3,4,Inc,Mccann Group,88318 Bennett Mall,New Justin,ME,Moldova,81059,2efb97bb-0201-43c4-a8f9-60f0e4bcdcdd,83-2594745,...,(273)246-8370,001-496-823-5292x7963,maureen15@example.net,"Soto, Kim and Chen",Guinea-Bissau,True,Pham Group,49da031c-1600-48c7-a271-d88dd55ea7d3,Dan Morgan,1977-03-07
4,5,Ltd,"Stevens, Mason and King",13224 Taylor Ramp Suite 051,Dianeshire,WI,Reunion,09855,6f391da3-3dba-4f9e-bf22-4bfdd21bdc14,93-6710664,...,(485)723-9022x8306,500.317.0765x6862,waltergarcia@example.net,Ray Inc,Indonesia,False,Wood-Reynolds,d41b7e56-02ff-4dbd-a8d7-875af47366d8,Marcus Dawson,1993-04-07

### Check and change data types of columns

In [57]:
print(f8957_df.dtypes)

unique_id                                                       int64
financial_institution_type                                     object
business_name                                                  object
business_mailing_address                                       object
business_mailing_address_city                                  object
business_mailing_address_state                                 object
business_mailing_address_country                               object
business_mailing_address_zip                                   object
country_tax_ID                                                 object
qi_ein                                                         object
wp_ein                                                         object
wt_ein                                                         object
us_ein                                                         object
business_title_of_ro                                           object
ro_lastname                                                    object
ro_firstname                                                   object
ro_middlename                                                  object
ro_address_city                                                object
ro_address_country                                             object
ro_business_address_line1                                      object
ro_business_address_line2                                      object
ro_address_state                                               object
ro_address_zip                                                 object
ro_business_telephone_number                                   object
ro_business_fax_number                                         object
ro_business_email_address                                      object
po_lastname                                                    object
po_firstname                                                   object
po_middlename                                                  object
po_address_city                                                object
po_address_country                                             object
po_business_address_line1                                      object
po_business_address_line2                                      object
po_address_state                                               object
po_address_zip                                                 object
po_business_telephone_number                                   object
po_business_fax_number                                         object
po_business_email_address                                      object
name_of_member_financial_institution                           object
country_of_member_financial_institution                        object
fi_common_parent_entity_of_expanded_affiliated_group?            bool
name_of_expanded_affiliated_groups_common_parent_entity        object
fatca_id_of_expanded_affiliated_groups_common_parent_entity    object
signature_name                                                 object
signature_date                                                 object
dtype: object

In [ ]:
f8957_df.info()

In [59]:
# Convert all columns to data type string except for one

def convert_columns_to_string(df, exclude_column):
    for col in df.columns:
        if col != exclude_column:
            df[col] = df[col].astype(str)
    return df

In [63]:
f8957_df = convert_columns_to_string(f8957_df, 'fi_common_parent_entity_of_expanded_affiliated_group?')

In [ ]:
print(f8957_df.dtypes)

In [66]:
# Verify all objects in correct columns are strings

def verify_string_columns(df, exclude_column):
    verification_results = {}
    for col in df.columns:
        if col != exclude_column:
            verification_results[col] = df[col].apply(lambda x: isinstance(x, str)).all()
        else:
            verification_results[col] = 'Excluded'
    return verification_results

# Verify the data types
verification_results = verify_string_columns(f8957_df, 'fi_common_parent_entity_of_expanded_affiliated_group?')

# Display the modified DataFrame, its data types, and verification results
print(f8957_df.dtypes)
print(verification_results)

unique_id                                                      object
financial_institution_type                                     object
business_name                                                  object
business_mailing_address                                       object
business_mailing_address_city                                  object
business_mailing_address_state                                 object
business_mailing_address_country                               object
business_mailing_address_zip                                   object
country_tax_ID                                                 object
qi_ein                                                         object
wp_ein                                                         object
wt_ein                                                         object
us_ein                                                         object
business_title_of_ro                                           object
ro_lastname                                                    object
ro_firstname                                                   object
ro_middlename                                                  object
ro_address_city                                                object
ro_address_country                                             object
ro_business_address_line1                                      object
ro_business_address_line2                                      object
ro_address_state                                               object
ro_address_zip                                                 object
ro_business_telephone_number                                   object
ro_business_fax_number                                         object
ro_business_email_address                                      object
po_lastname                                                    object
po_firstname                                                   object
po_middlename                                                  object
po_address_city                                                object
po_address_country                                             object
po_business_address_line1                                      object
po_business_address_line2                                      object
po_address_state                                               object
po_address_zip                                                 object
po_business_telephone_number                                   object
po_business_fax_number                                         object
po_business_email_address                                      object
name_of_member_financial_institution                           object
country_of_member_financial_institution                        object
fi_common_parent_entity_of_expanded_affiliated_group?            bool
name_of_expanded_affiliated_groups_common_parent_entity        object
fatca_id_of_expanded_affiliated_groups_common_parent_entity    object
signature_name                                                 object
signature_date                                                 object
dtype: object
{'unique_id': True, 'financial_institution_type': True, 'business_name': True, 'business_mailing_address': True, 'business_mailing_address_city': True, 'business_mailing_address_state': True, 'business_mailing_address_country': True, 'business_mailing_address_zip': True, 'country_tax_ID': True, 'qi_ein': True, 'wp_ein': True, 'wt_ein': True, 'us_ein': True, 'business_title_of_ro': True, 'ro_lastname': True, 'ro_firstname': True, 'ro_middlename': True, 'ro_address_city': True, 'ro_address_country': True, 'ro_business_address_line1': True, 'ro_business_address_line2': True, 'ro_address_state': True, 'ro_address_zip': True, 'ro_business_telephone_number': True, 'ro_business_fax_number': True, 'ro_business_email_address': True, 'po_lastname': True, 'po_firstname': True, 'po_middlename': True, 'po_address_city': True, 'po_address_country': True, 'po_business_address_line1': True, 'po_business_address_line2': True, 'po_address_state': True, 'po_address_zip': True, 'po_business_telephone_number': True, 'po_business_fax_number': True, 'po_business_email_address': True, 'name_of_member_financial_institution': True, 'country_of_member_financial_institution': True, 'fi_common_parent_entity_of_expanded_affiliated_group?': 'Excluded', 'name_of_expanded_affiliated_groups_common_parent_entity': True, 'fatca_id_of_expanded_affiliated_groups_common_parent_entity': True, 'signature_name': True, 'signature_date': True}

### Cleaning and standardizing telephone numbers

In [ ]:
 # Remove non-numeric characters
    phone = re.sub(r'\D', '', phone)