# Splink Practice on first_initial dataset

Amanda Rodgers

October 24, 2024

Note: There are 1000 transactions with about 50 duplicates where the only change is the first name is first initial

In [6]:
pip install pandas

Requirement already satisfied: pandas in /opt/anaconda3/lib/python3.11/site-packages (2.1.4)
Requirement already satisfied: numpy<2,>=1.23.2 in /opt/anaconda3/lib/python3.11/site-packages (from pandas) (1.26.4)
Requirement already satisfied: python-dateutil>=2.8.2 in /opt/anaconda3/lib/python3.11/site-packages (from pandas) (2.8.2)
Requirement already satisfied: pytz>=2020.1 in /opt/anaconda3/lib/python3.11/site-packages (from pandas) (2023.3.post1)
Requirement already satisfied: tzdata>=2022.1 in /opt/anaconda3/lib/python3.11/site-packages (from pandas) (2023.3)
Requirement already satisfied: six>=1.5 in /opt/anaconda3/lib/python3.11/site-packages (from python-dateutil>=2.8.2->pandas) (1.16.0)
Note: you may need to restart the kernel to use updated packages.

In [7]:
pip install splink

Requirement already satisfied: splink in /opt/anaconda3/lib/python3.11/site-packages (4.0.4)
Requirement already satisfied: Jinja2>=3.0.3 in /opt/anaconda3/lib/python3.11/site-packages (from splink) (3.1.3)
Requirement already satisfied: altair<6.0.0,>=5.0.1 in /opt/anaconda3/lib/python3.11/site-packages (from splink) (5.0.1)
Requirement already satisfied: duckdb>=0.9.2 in /opt/anaconda3/lib/python3.11/site-packages (from splink) (1.1.3)
Requirement already satisfied: igraph>=0.11.2 in /opt/anaconda3/lib/python3.11/site-packages (from splink) (0.11.8)
Requirement already satisfied: jsonschema>=3.2 in /opt/anaconda3/lib/python3.11/site-packages (from splink) (4.19.2)
Requirement already satisfied: numpy>=1.17.3 in /opt/anaconda3/lib/python3.11/site-packages (from splink) (1.26.4)
Requirement already satisfied: pandas>1.3.5 in /opt/anaconda3/lib/python3.11/site-packages (from splink) (2.1.4)
Requirement already satisfied: sqlglot>=13.0.0 in /opt/anaconda3/lib/python3.11/site-packages (from splink) (25.28.0)
Requirement already satisfied: toolz in /opt/anaconda3/lib/python3.11/site-packages (from altair<6.0.0,>=5.0.1->splink) (0.12.0)
Requirement already satisfied: texttable>=1.6.2 in /opt/anaconda3/lib/python3.11/site-packages (from igraph>=0.11.2->splink) (1.7.0)
Requirement already satisfied: MarkupSafe>=2.0 in /opt/anaconda3/lib/python3.11/site-packages (from Jinja2>=3.0.3->splink) (2.1.3)
Requirement already satisfied: attrs>=22.2.0 in /opt/anaconda3/lib/python3.11/site-packages (from jsonschema>=3.2->splink) (23.1.0)
Requirement already satisfied: jsonschema-specifications>=2023.03.6 in /opt/anaconda3/lib/python3.11/site-packages (from jsonschema>=3.2->splink) (2023.7.1)
Requirement already satisfied: referencing>=0.28.4 in /opt/anaconda3/lib/python3.11/site-packages (from jsonschema>=3.2->splink) (0.30.2)
Requirement already satisfied: rpds-py>=0.7.1 in /opt/anaconda3/lib/python3.11/site-packages (from jsonschema>=3.2->splink) (0.10.6)
Requirement already satisfied: python-dateutil>=2.8.2 in /opt/anaconda3/lib/python3.11/site-packages (from pandas>1.3.5->splink) (2.8.2)
Requirement already satisfied: pytz>=2020.1 in /opt/anaconda3/lib/python3.11/site-packages (from pandas>1.3.5->splink) (2023.3.post1)
Requirement already satisfied: tzdata>=2022.1 in /opt/anaconda3/lib/python3.11/site-packages (from pandas>1.3.5->splink) (2023.3)
Requirement already satisfied: six>=1.5 in /opt/anaconda3/lib/python3.11/site-packages (from python-dateutil>=2.8.2->pandas>1.3.5->splink) (1.16.0)
Note: you may need to restart the kernel to use updated packages.

In [11]:
import pandas as pd

In [12]:
# Load the CSV file into a DataFrame
df = pd.read_csv('/Users/amandarodgers/code/splink_practice/first_name_initial_edge_case/clean_data.csv')

# Display the first few rows of the DataFrame to verify that the data has been loaded correctly
df.head(5)

,unique_id,transaction_id,sender_name,receiver_name,sender_address_full,sender_zipcode,receiver_address_full,receiver_zipcode,transaction_amount
0,1,1,Jessica Obrien,Stephanie Morales,Japan,NaN,"4466 Marc Village, Port Joseph, UT 69096",950.0,266977.82
1,2,2,James Andrews,Elizabeth Mcmahon,NaN,NaN,"900 Webster Street Suite 761, North Mary, TN 8...",718.0,936654.59
2,3,3,Joseph Ross,Sheryl Pope,"773 Sarah Extension Apartment 571, Williamsbur...",NaN,"75403 Raymond Flat Apartment 085, Jenniferstad...",99376.0,648035.39
3,4,4,Heather Smith,Joanne Smith,United States,NaN,"8302 Hicks Point Apartment 917, Kirkshire, MP ...",665.0,609131.01
4,5,5,Anna Elliott,Casey Le,United States,NaN,"1690 Eric Summit Apartment 545, Port Evelyn, I...",NaN,171138.65

In [13]:
df.describe()

         unique_id  transaction_id  receiver_zipcode  transaction_amount
count  1000.000000     1000.000000        950.000000         1000.000000
mean    500.500000      500.500000      35720.505263       517967.184030
std     288.819436      288.819436      33648.960293       288695.225009
min       1.000000        1.000000          5.000000          405.940000
25%     250.750000      250.750000        788.500000       266470.872500
50%     500.500000      500.500000      30501.000000       530603.020000
75%     750.250000      750.250000      64670.000000       762993.962500
max    1000.000000     1000.000000      99925.000000       999907.830000

In [14]:
print(df.dtypes)

unique_id                  int64
transaction_id             int64
sender_name               object
receiver_name             object
sender_address_full       object
sender_zipcode            object
receiver_address_full     object
receiver_zipcode         float64
transaction_amount       float64
dtype: object

In [15]:
df['receiver_zipcode'] = df['receiver_zipcode'].astype(str)

In [16]:
print(df.dtypes)

unique_id                  int64
transaction_id             int64
sender_name               object
receiver_name             object
sender_address_full       object
sender_zipcode            object
receiver_address_full     object
receiver_zipcode          object
transaction_amount       float64
dtype: object

In [17]:
import pandas as pd
import numpy as np

def standardize_missing_values(df):
    """
    Standardize cells containing 'nan', 'Nan', 'None', or other representations of missing values to true null values (NaN).
    """
    # Replace 'nan', 'Nan', 'None', and other representations with np.nan
    df.replace(['nan', 'Nan', 'None', 'xx', None], np.nan, inplace=True)
    
    return df

df = standardize_missing_values(df)

In [18]:
df.head(10)

,unique_id,transaction_id,sender_name,receiver_name,sender_address_full,sender_zipcode,receiver_address_full,receiver_zipcode,transaction_amount
0,1,1,Jessica Obrien,Stephanie Morales,Japan,NaN,"4466 Marc Village, Port Joseph, UT 69096",950.0,266977.82
1,2,2,James Andrews,Elizabeth Mcmahon,NaN,NaN,"900 Webster Street Suite 761, North Mary, TN 8...",718.0,936654.59
2,3,3,Joseph Ross,Sheryl Pope,"773 Sarah Extension Apartment 571, Williamsbur...",NaN,"75403 Raymond Flat Apartment 085, Jenniferstad...",99376.0,648035.39
3,4,4,Heather Smith,Joanne Smith,United States,NaN,"8302 Hicks Point Apartment 917, Kirkshire, MP ...",665.0,609131.01
4,5,5,Anna Elliott,Casey Le,United States,NaN,"1690 Eric Summit Apartment 545, Port Evelyn, I...",NaN,171138.65
5,6,6,Thomas Rodriguez,Blake Olsen,"5560 Martin Isle Apartment 590, North Steven, ...",NaN,NaN,54839.0,729126.80
6,7,7,Robert Price,Cassandra Lambert,"561 Robles Loop, Thomasville, PA 72004",45510,OM,51834.0,163402.49
7,8,8,Ashley Jordan,Joseph Hudson,United States,NaN,NaN,NaN,379455.44
8,9,9,Erin Smith,Maria Flynn,United States,NaN,"USS Jennings, FPO AP 07178",98.0,989523.35
9,10,10,Sara Andrade,Gabriel Campos,United States,NaN,"Washington, IE",68768.0,639999.76

In [19]:
def add_sender_first_name(df):
    """
    Add a new column called sender_first_name next to the sender_name column.
    The sender_first_name column contains the first name extracted from the sender_name column.
    """
    # Split the sender_name column into two parts
    name_split = df['sender_name'].str.split(n=1, expand=True)
    
    # Assign the first part to sender_first_name
    df['sender_first_name'] = name_split[0]
    
    # Reorder columns to place sender_first_name next to sender_name
    cols = df.columns.tolist()
    sender_name_index = cols.index('sender_name')
    cols.insert(sender_name_index + 1, cols.pop(cols.index('sender_first_name')))
    df = df[cols]
    
    return df

In [20]:
df = add_sender_first_name(df)
df

,unique_id,transaction_id,sender_name,sender_first_name,receiver_name,sender_address_full,sender_zipcode,receiver_address_full,receiver_zipcode,transaction_amount
0,1,1,Jessica Obrien,Jessica,Stephanie Morales,Japan,NaN,"4466 Marc Village, Port Joseph, UT 69096",950.0,266977.82
1,2,2,James Andrews,James,Elizabeth Mcmahon,NaN,NaN,"900 Webster Street Suite 761, North Mary, TN 8...",718.0,936654.59
2,3,3,Joseph Ross,Joseph,Sheryl Pope,"773 Sarah Extension Apartment 571, Williamsbur...",NaN,"75403 Raymond Flat Apartment 085, Jenniferstad...",99376.0,648035.39
3,4,4,Heather Smith,Heather,Joanne Smith,United States,NaN,"8302 Hicks Point Apartment 917, Kirkshire, MP ...",665.0,609131.01
4,5,5,Anna Elliott,Anna,Casey Le,United States,NaN,"1690 Eric Summit Apartment 545, Port Evelyn, I...",NaN,171138.65
...,...,...,...,...,...,...,...,...,...,...
995,996,996,S White,S,Christine Morales,United States,NaN,NaN,62884.0,443383.09
996,997,997,T Grant,T,Lance Brown,Turks and Caicos Islands,NaN,"Idaho, AU",180.0,950555.17
997,998,998,S Pratt,S,Jodi Valenzuela,Israel,NaN,"97114 Kevin Views, East Charles, WI 33699",82159.0,855450.19
998,999,999,J Andrews,J,Elizabeth Mcmahon,NaN,NaN,"900 Webster Street Suite 761, North Mary, TN 8...",718.0,936654.59
999,1000,1000,J Ross,J,Sheryl Pope,"773 Sarah Extension Apartment 571, Williamsbur...",NaN,"75403 Raymond Flat Apartment 085, Jenniferstad...",99376.0,648035.39

In [21]:
def add_sender_last_name(df):
    """
    Add a new column called sender_last_name next to the sender_name column.
    The sender_last_name column contains the last name extracted from the sender_name column.
    """
    # Split the sender_name column into parts
    name_split = df['sender_name'].str.split()
    
    # Assign the last part to sender_last_name
    df['sender_last_name'] = name_split.str[-1]
    
    # Reorder columns to place sender_last_name next to sender_name
    cols = df.columns.tolist()
    sender_name_index = cols.index('sender_name')
    cols.insert(sender_name_index + 2, cols.pop(cols.index('sender_last_name')))
    df = df[cols]
    
    return df

In [22]:
df = add_sender_last_name(df)
df

,unique_id,transaction_id,sender_name,sender_first_name,sender_last_name,receiver_name,sender_address_full,sender_zipcode,receiver_address_full,receiver_zipcode,transaction_amount
0,1,1,Jessica Obrien,Jessica,Obrien,Stephanie Morales,Japan,NaN,"4466 Marc Village, Port Joseph, UT 69096",950.0,266977.82
1,2,2,James Andrews,James,Andrews,Elizabeth Mcmahon,NaN,NaN,"900 Webster Street Suite 761, North Mary, TN 8...",718.0,936654.59
2,3,3,Joseph Ross,Joseph,Ross,Sheryl Pope,"773 Sarah Extension Apartment 571, Williamsbur...",NaN,"75403 Raymond Flat Apartment 085, Jenniferstad...",99376.0,648035.39
3,4,4,Heather Smith,Heather,Smith,Joanne Smith,United States,NaN,"8302 Hicks Point Apartment 917, Kirkshire, MP ...",665.0,609131.01
4,5,5,Anna Elliott,Anna,Elliott,Casey Le,United States,NaN,"1690 Eric Summit Apartment 545, Port Evelyn, I...",NaN,171138.65
...,...,...,...,...,...,...,...,...,...,...,...
995,996,996,S White,S,White,Christine Morales,United States,NaN,NaN,62884.0,443383.09
996,997,997,T Grant,T,Grant,Lance Brown,Turks and Caicos Islands,NaN,"Idaho, AU",180.0,950555.17
997,998,998,S Pratt,S,Pratt,Jodi Valenzuela,Israel,NaN,"97114 Kevin Views, East Charles, WI 33699",82159.0,855450.19
998,999,999,J Andrews,J,Andrews,Elizabeth Mcmahon,NaN,NaN,"900 Webster Street Suite 761, North Mary, TN 8...",718.0,936654.59
999,1000,1000,J Ross,J,Ross,Sheryl Pope,"773 Sarah Extension Apartment 571, Williamsbur...",NaN,"75403 Raymond Flat Apartment 085, Jenniferstad...",99376.0,648035.39

In [23]:
#See how much missing data there is
from splink.exploratory import completeness_chart
from splink import DuckDBAPI
db_api = DuckDBAPI()
completeness_chart(df, db_api=db_api)

alt.LayerChart(...)

In [24]:
# For each column, list the most top 10 common values and least 5 common values
from splink.exploratory import profile_columns

profile_columns(df, db_api=DuckDBAPI(), top_n=10, bottom_n=5)

alt.VConcatChart(...)

In [25]:
print(df.dtypes)

unique_id                  int64
transaction_id             int64
sender_name               object
sender_first_name         object
sender_last_name          object
receiver_name             object
sender_address_full       object
sender_zipcode            object
receiver_address_full     object
receiver_zipcode          object
transaction_amount       float64
dtype: object

In [26]:
# Create record comparisons where the initial of the sender_first_name and the sender_last_name match 
from splink import block_on
block_on("substr(sender_first_name, 1, 2)", "sender_last_name")

In [27]:
# Block_on sender_name and receiver_name and count how many comparisons it will produce to calculate
from splink.blocking_analysis import count_comparisons_from_blocking_rule

db_api = DuckDBAPI()

br = block_on("substr(sender_first_name, 1, 2)", "sender_last_name")

counts = count_comparisons_from_blocking_rule(
    table_or_tables=df,
    blocking_rule=br,
    link_type="dedupe_only",
    db_api=db_api,
)

counts

{'number_of_comparisons_generated_pre_filter_conditions': 1074,
 'number_of_comparisons_to_be_scored_post_filter_conditions': 37,
 'filter_conditions_identified': '',
 'equi_join_conditions_identified': 'SUBSTRING(l.sender_first_name, 1, 2) = SUBSTRING(r.sender_first_name, 1, 2) AND l."sender_last_name" = r."sender_last_name"',
 'link_type_join_condition': 'where l."unique_id" < r."unique_id"'}

In [45]:
# Count the number of comparisons
counts = count_comparisons_from_blocking_rule(
    table_or_tables=df,
    blocking_rule=br,
    link_type="dedupe_only",
    db_api=db_api,
)

# Display the counts
print(counts)

{'number_of_comparisons_generated_pre_filter_conditions': 1074, 'number_of_comparisons_to_be_scored_post_filter_conditions': 37, 'filter_conditions_identified': '', 'equi_join_conditions_identified': 'SUBSTRING(l.sender_first_name, 1, 2) = SUBSTRING(r.sender_first_name, 1, 2) AND l."sender_last_name" = r."sender_last_name"', 'link_type_join_condition': 'where l."unique_id" < r."unique_id"'}

In [28]:
# Find any skewed data
from splink.blocking_analysis import n_largest_blocks

result = n_largest_blocks(    table_or_tables=df,
    blocking_rule= block_on("substr(sender_first_name, 1, 2)", "sender_last_name"),
    link_type="dedupe_only",
    db_api=db_api,
    n_largest=3
    )

result.as_pandas_dataframe()

  key_0   key_1  count_l  count_r  block_count
0    Er   Smith        3        3            9
1    Ja  Miller        3        3            9
2    St   Smith        3        3            9

Next steps: 
- Did above: blocking rules to generate pairwise record comparisons
- Train linkage model 
- Estimate a probabilistic linkage model to score each of the comparisons above ( first initial and last name)
    - to learn the relative importance of different parts of your data for the purpose of data linking
    - example: dob is stronger indicator that two rows are same entity than gender
- The relative importance of different information is captured in the (partial) 'match weights', which can be learned from your data.
- The match weights are are derived from the m and u parameters of the underlying Fellegi Sunter model.
- The concept of a Comparison has a specific definition within Splink: it defines how data from one or more input columns is compared.
    - For example, one Comparison may represent how similarity is assessed for a person's date of birth.

In [29]:
# Example of a generic Splink comparison function using fuzzy matching and levenshtein distance

import splink.comparison_library as cl

city_comparison = cl.LevenshteinAtThresholds("city", 2)
print(city_comparison.get_comparison("duckdb").human_readable_description)

Comparison 'LevenshteinAtThresholds' of "city".
Similarity is assessed using the following ComparisonLevels:
    - 'city is NULL' with SQL rule: "city_l" IS NULL OR "city_r" IS NULL
    - 'Exact match on city' with SQL rule: "city_l" = "city_r"
    - 'Levenshtein distance of city <= 2' with SQL rule: levenshtein("city_l", "city_r") <= 2
    - 'All other comparisons' with SQL rule: ELSE

In [30]:
# Step: Specify linkage model with your own comparisons and blocking rules
# Comparisons are specified as part of the Splink settings, a Python dictionary which controls all of the 
# configuration of a Splink model:
from splink import Linker, SettingsCreator, block_on, DuckDBAPI

settings = SettingsCreator(
    link_type="dedupe_only",
    comparisons=[
        cl.NameComparison("sender_first_name"),
        cl.NameComparison("sender_last_name"),
        cl.LevenshteinAtThresholds("sender_address_full", 1),
        cl.ExactMatch("sender_last_name").configure(term_frequency_adjustments=True)
    ],
    # will only check for duplicates amongst records where either the first name first intial AND last name or lastname is identical
    blocking_rules_to_generate_predictions=[
        block_on("substr(sender_first_name, 1, 2)", "sender_last_name"),
        block_on("sender_last_name"),

    ],
    retain_intermediate_calculation_columns=True,
)

linker = Linker(df, settings, db_api=DuckDBAPI())

In [31]:
# Estimate the probability_two_random_records_match
# The u values are the proportion of records falling into each ComparisonLevel amongst truly non-matching records.
# The m values are the proportion of records falling into each ComparisonLevel amongst truly matching records
# TO DO: need to look more into how to determine this estimation: https://github.com/moj-analytical-services/splink/issues/462#issuecomment-1227027995
# Whatever percentage you set the recall to you are saying that the deterministic_rules you set should cover about that percentage of true matches

deterministic_rules = [
    block_on("substr(sender_first_name, 1, 2)"),
    block_on("sender_last_name")
]

linker.training.estimate_probability_two_random_records_match(deterministic_rules, recall=0.2)

Probability two random records match is estimated to be  0.116.
This means that amongst all possible pairwise record comparisons, one in 8.64 are expected to match.  With 499,500 total possible comparisons, we expect a total of around 57,840.00 matching pairs

In [32]:
# Estimate u parameter
linker.training.estimate_u_using_random_sampling(max_pairs=1e6)

You are using the default value for `max_pairs`, which may be too small and thus lead to inaccurate estimates for your model's u-parameters. Consider increasing to 1e8 or 1e9, which will result in more accurate estimates, but with a longer run time.
----- Estimating u probabilities using random sampling -----

Estimated u probabilities using random sampling

Your model is not yet fully trained. Missing estimates for:
    - sender_first_name (no m values are trained).
    - sender_last_name (no m values are trained).
    - sender_address_full (no m values are trained).
    - sender_last_name (no m values are trained).

In [33]:
# Estimate m parameter
# To do: check if transaction_id would be best choice, how do you choose which column?
linker.training.estimate_m_from_label_column("transaction_id")

---- Estimating m probabilities using from column transaction_id -----
m probability not trained for sender_first_name - Exact match on sender_first_name (comparison vector value: 4). This usually means the comparison level was never observed in the training data.
m probability not trained for sender_first_name - Jaro-Winkler distance of sender_first_name >= 0.92 (comparison vector value: 3). This usually means the comparison level was never observed in the training data.
m probability not trained for sender_first_name - Jaro-Winkler distance of sender_first_name >= 0.88 (comparison vector value: 2). This usually means the comparison level was never observed in the training data.
m probability not trained for sender_first_name - Jaro-Winkler distance of sender_first_name >= 0.7 (comparison vector value: 1). This usually means the comparison level was never observed in the training data.
m probability not trained for sender_first_name - All other comparisons (comparison vector value: 0). This usually means the comparison level was never observed in the training data.
m probability not trained for sender_last_name - Exact match on sender_last_name (comparison vector value: 4). This usually means the comparison level was never observed in the training data.
m probability not trained for sender_last_name - Jaro-Winkler distance of sender_last_name >= 0.92 (comparison vector value: 3). This usually means the comparison level was never observed in the training data.
m probability not trained for sender_last_name - Jaro-Winkler distance of sender_last_name >= 0.88 (comparison vector value: 2). This usually means the comparison level was never observed in the training data.
m probability not trained for sender_last_name - Jaro-Winkler distance of sender_last_name >= 0.7 (comparison vector value: 1). This usually means the comparison level was never observed in the training data.
m probability not trained for sender_last_name - All other comparisons (comparison vector value: 0). This usually means the comparison level was never observed in the training data.
m probability not trained for sender_address_full - Exact match on sender_address_full (comparison vector value: 2). This usually means the comparison level was never observed in the training data.
m probability not trained for sender_address_full - Levenshtein distance of sender_address_full <= 1 (comparison vector value: 1). This usually means the comparison level was never observed in the training data.
m probability not trained for sender_address_full - All other comparisons (comparison vector value: 0). This usually means the comparison level was never observed in the training data.
m probability not trained for sender_last_name - Exact match on sender_last_name (comparison vector value: 1). This usually means the comparison level was never observed in the training data.
m probability not trained for sender_last_name - All other comparisons (comparison vector value: 0). This usually means the comparison level was never observed in the training data.

Your model is not yet fully trained. Missing estimates for:
    - sender_first_name (no m values are trained).
    - sender_last_name (no m values are trained).
    - sender_address_full (no m values are trained).
    - sender_last_name (no m values are trained).

In [34]:
# Check available methods to linker object to debug m parameter
print(dir(linker))

['__class__', '__deepcopy__', '__delattr__', '__dict__', '__dir__', '__doc__', '__eq__', '__format__', '__ge__', '__getattribute__', '__getstate__', '__gt__', '__hash__', '__init__', '__init_subclass__', '__le__', '__lt__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__slotnames__', '__str__', '__subclasshook__', '__weakref__', '_cache_uid', '_check_for_valid_settings', '_concat_table_column_names', '_db_api', '_db_schema', '_debug_mode', '_detect_blocking_rules_for_em_training', '_detect_blocking_rules_for_prediction', '_em_training_sessions', '_find_blocking_rules_below_threshold', '_get_labels_tablename_from_input', '_infinity_expression', '_input_columns', '_input_tables_dict', '_intermediate_table_cache', '_populate_m_u_from_trained_values', '_populate_probability_two_random_records_match_from_trained_values', '_predict_warning', '_raise_error_if_necessary_accuracy_columns_not_computed', '_raise_error_if_necessary_waterfall_columns_not_computed', '_random_sample_sql', '_register_input_tables', '_self_link', '_settings_obj', '_source_dataset_column_already_exists', '_sql_dialect', '_sql_dialect_str', '_table_to_splink_dataframe', '_two_dataset_link_only', '_validate_input_dfs', '_validate_settings', 'clustering', 'evaluation', 'inference', 'misc', 'table_management', 'training', 'visualisations']

In [35]:
# View final estimated match weights
linker.visualisations.match_weights_chart()

alt.VConcatChart(...)

In [36]:
# Visualize m and u parameters
linker.visualisations.m_u_parameters_chart()

alt.HConcatChart(...)

In [37]:
# Compare the estimates that were produced by the different EM training sessions
linker.visualisations.parameter_estimate_comparisons_chart()

alt.Chart(...)

In [38]:
# Save model in json file to use for later
settings = linker.misc.save_model_to_json(
    "/Users/amandarodgers/code/splink_practice/saved_model_from_demo.json", overwrite=True
)

In [39]:
# Find unlinkable rows that have insufficient data
linker.evaluation.unlinkables_chart()

alt.LayerChart(...)

Next Step: Load the estimated model and use it to make predictions of which pairwise record comparisons match

In [40]:
from splink import Linker, DuckDBAPI, splink_datasets

import pandas as pd

pd.options.display.max_columns = 1000

db_api = DuckDBAPI()
df = df

In [47]:
# Load estimated model
import json

file_path = "/Users/amandarodgers/code/splink_practice/saved_model_from_demo.json"

# Open the file and load the settings
with open(file_path, 'r') as f:
    settings = json.load(f)

linker = Linker(df, settings, db_api=DuckDBAPI())

In [48]:
# Run the model which will: 
# Generate all pairwise record comparisons that match at least one of the blocking_rules_to_generate_predictions
# Use the rules specified in the Comparisons to evaluate the similarity of the input data
# Use the estimated match weights, applying term frequency adjustments where requested to produce the final match_weight and match_probability scores
# Optionally, a threshold_match_probability or threshold_match_weight can be provided, which will drop any row where the predicted score is below the threshold.

df_predictions = linker.inference.predict(threshold_match_probability=0.2)
predictions_df = df_predictions.as_pandas_dataframe(limit=1000)

Blocking time: 0.00 seconds
Predict time: 0.10 seconds

 -- WARNING --
You have called predict(), but there are some parameter estimates which have neither been estimated or specified in your settings dictionary.  To produce predictions the following untrained trained parameters will use default values.
Comparison: 'sender_first_name':
    m values not fully trained
Comparison: 'sender_last_name':
    m values not fully trained
Comparison: 'sender_address_full':
    m values not fully trained
Comparison: 'sender_last_name':
    m values not fully trained

In [49]:
predictions_df.head(10)

,match_weight,match_probability,unique_id_l,unique_id_r,sender_first_name_l,sender_first_name_r,gamma_sender_first_name,tf_sender_first_name_l,tf_sender_first_name_r,bf_sender_first_name,bf_tf_adj_sender_first_name,sender_last_name_l,sender_last_name_r,gamma_sender_last_name,tf_sender_last_name_l,tf_sender_last_name_r,bf_sender_last_name,bf_tf_adj_sender_last_name,sender_address_full_l,sender_address_full_r,gamma_sender_address_full,bf_sender_address_full,match_key
0,-0.367929,0.436586,15,31,Barbara,Kimberly,0,0.004,0.006,0.012913,1.0,Martinez,Martinez,4,0.009,0.009,564.910714,0.186854,"Unit 6599 Box 9095, DPO AP 02806",United States,0,0.041125,1
1,4.451605,0.956296,12,34,Michael,Anne,0,0.018,0.001,0.012913,1.0,Wilson,Wilson,4,0.013,0.013,564.910714,0.129360,United States,United States,2,2.422881,1
2,1.971921,0.796868,24,35,Derrick,Ashley,0,0.002,0.008,0.012913,1.0,Nelson,Nelson,4,0.004,0.004,564.910714,0.420420,Sudan,United States,0,0.041125,1
3,4.451605,0.956296,34,39,Anne,John,0,0.001,0.017,0.012913,1.0,Wilson,Wilson,4,0.013,0.013,564.910714,0.129360,United States,United States,2,2.422881,1
4,2.136522,0.814712,9,47,Erin,Andrew,0,0.005,0.007,0.012913,1.0,Smith,Smith,4,0.029,0.029,564.910714,0.057989,United States,United States,2,2.422881,1
5,-0.671935,0.385623,26,62,Nathan,Stanley,0,0.003,0.001,0.012913,1.0,Harris,Harris,4,0.010,0.010,564.910714,0.168168,"57641 Benjamin Street Suite 975, Lake Nancy, A...",United States,0,0.041125,1
6,3.174881,0.900309,39,65,John,Courtney,0,0.017,0.004,0.012913,1.0,Wilson,Wilson,4,0.013,0.013,564.910714,0.129360,United States,None,-1,1.000000,1
7,0.859799,0.644733,9,82,Erin,Breanna,0,0.005,0.001,0.012913,1.0,Smith,Smith,4,0.029,0.029,564.910714,0.057989,United States,None,-1,1.000000,1
8,7.208628,0.993285,28,85,Jason,Steven,0,0.011,0.007,0.012913,1.0,Guzman,Guzman,4,0.005,0.005,564.910714,0.336336,United States,United States,2,2.422881,1
9,2.136522,0.814712,9,92,Erin,Jonathan,0,0.005,0.003,0.012913,1.0,Smith,Smith,4,0.029,0.029,564.910714,0.057989,United States,United States,2,2.422881,1

In [ ]:
# Export predictions df to csv
predictions_df.to_csv('predictions_first_initial.csv', index=False)
print("Predictions df converted to predictions_first_initial.csv ")

In [ ]:
# Change to clustered result
clusters = linker.clustering.cluster_pairwise_predictions_at_threshold(
    df_predictions, threshold_match_probability=0.5
)
clusters.as_pandas_dataframe(limit=10)

In [ ]:
# Can use SQL too
sql = f"""
select *
from {df_predictions.physical_name}
limit 100
"""
linker.misc.query_sql(sql)

# Visualizing Predictions

In [ ]:
# Waterfall chart provides a means of visualising individual predictions to understand how Splink computed the final matchweight for a particular pairwise record comparison
records_to_view = df_predictions.as_record_dict(limit=100)
linker.visualisations.waterfall_chart(records_to_view, filter_nulls=False)

In [ ]:
# An in-depth video describing how to interpret the dashboard can be found here.

linker.visualisations.comparison_viewer_dashboard(df_predictions, "scv.html", overwrite=True)

# You can view the scv.html file in your browser, or inline in a notbook as follows
from IPython.display import IFrame

IFrame(src="./scv.html", width="100%", height=1200)

In [ ]:
# Cluster studio is an interactive dashboards that visualises the results of clustering your predictions.

df_clusters = linker.clustering.cluster_pairwise_predictions_at_threshold(
    df_predictions, threshold_match_probability=0.5
)

linker.visualisations.cluster_studio_dashboard(
    df_predictions,
    df_clusters,
    "cluster_studio.html",
    sampling_method="by_cluster_size",
    overwrite=True,
)

# You can view the scv.html file in your browser, or inline in a notbook as follows
from IPython.display import IFrame

IFrame(src="./cluster_studio.html", width="100%", height=1000)

In [ ]:
# The labels file contains a list of pairwise comparisons which represent matches and non-matches.

from splink.datasets import splink_dataset_labels

df_labels = splink_dataset_labels.fake_1000_labels
labels_table = linker.table_management.register_labels_table(df_labels)
df_labels.head(5)

In [ ]:
# Examples of false positives and negatives
splink_df = linker.evaluation.prediction_errors_from_labels_table(
    labels_table, include_false_negatives=True, include_false_positives=False
)
false_negatives = splink_df.as_record_dict(limit=5)
linker.visualisations.waterfall_chart(false_negatives)

In [ ]:
# False Positives
# Note I've picked a threshold match probability of 0.01 here because otherwise
# in this simple example there are no false positives

# TO DO: fix error
# ValueError: No comparison level with comparison vector value 4

splink_df = linker.evaluation.prediction_errors_from_labels_table(
    labels_table, include_false_negatives=False, include_false_positives=True, threshold_match_probability=0.01
)
false_postives = splink_df.as_record_dict(limit=5)
linker.visualisations.waterfall_chart(false_postives)

In [ ]:
# Splink includes an interactive dashboard that shows key accuracy statistics:
linker.evaluation.accuracy_analysis_from_labels_table(
    labels_table, output_type="threshold_selection", add_metrics=["f1"]
)

In [ ]:
# A ROC chart shows how the number of false positives and false negatives varies depending on the match threshold chosen. 
# The match threshold is the match weight chosen as a cutoff for which pairwise comparisons to accept as matches.

linker.evaluation.accuracy_analysis_from_labels_table(labels_table, output_type="roc")

In [ ]:
# Splink can also report the underlying table used to construct the ROC and precision recall curves.
roc_table = linker.evaluation.accuracy_analysis_from_labels_table(
    labels_table, output_type="table"
)
roc_table.as_pandas_dataframe(limit=5)

In [ ]:
# 'Unlinkable records' are records with such poor data quality they don't even link to themselves at a high enough probability to be accepted as matches

linker.evaluation.unlinkables_chart()

In [ ]:
# For this dataset and this trained model, we can see that most records are (theoretically) linkable: At a match weight 6, around around 99% of records could be linked to themselves.

# END