In [3]:
import pandas as pd
import random

# Generate random values for each column
principals = [random.randint(5000, 100000) for _ in range(100)]
inflations = [round(random.uniform(0.02, 0.09), 2) for _ in range(100)]
interests = [principal * inflation for principal, inflation in zip(principals, inflations)]

# Introduce incorrect interest values for 10% of the entries
num_wrong_entries = int(len(interests) * 0.1)
indices_to_change = random.sample(range(len(interests)), num_wrong_entries)
for idx in indices_to_change:
    interests[idx] = random.randint(5000, 100000)  # Assigning a random value

# Create DataFrame
data = {'Principal': principals, 'Inflation': inflations, 'Interest': interests}
df = pd.DataFrame(data)
df

    Principal  Inflation  Interest
0       33593       0.05   1679.65
1       36045       0.08   2883.60
2       10034       0.09    903.06
3       57439       0.09  85161.00
4       95748       0.04   3829.92
..        ...        ...       ...
95      68991       0.06   4139.46
96      35120       0.04   1404.80
97      32031       0.07   2242.17
98      63019       0.03   1890.57
99      26990       0.04   1079.60

[100 rows x 3 columns]

In [4]:
help(df.drop)

Help on method drop in module pandas.core.frame:

drop(labels: 'IndexLabel | None' = None, *, axis: 'Axis' = 0, index: 'IndexLabel | None' = None, columns: 'IndexLabel | None' = None, level: 'Level | None' = None, inplace: 'bool' = False, errors: 'IgnoreRaise' = 'raise') -> 'DataFrame | None' method of pandas.core.frame.DataFrame instance
    Drop specified labels from rows or columns.

    Remove rows or columns by specifying label names and corresponding
    axis, or by directly specifying index or column names. When using a
    multi-index, labels on different levels can be removed by specifying
    the level. See the :ref:`user guide <advanced.shown_levels>`
    for more information about the now unused levels.

    Parameters
    ----------
    labels : single label or list-like
        Index or column labels to drop. A tuple will be used as a single
        label and not treated as a list-like.
    axis : {0 or 'index', 1 or 'columns'}, default 0
        Whether to drop labels from the index (0 or 'index') or
        columns (1 or 'columns').
    index : single label or list-like
        Alternative to specifying axis (``labels, axis=0``
        is equivalent to ``index=labels``).
    columns : single label or list-like
        Alternative to specifying axis (``labels, axis=1``
        is equivalent to ``columns=labels``).
    level : int or level name, optional
        For MultiIndex, level from which the labels will be removed.
    inplace : bool, default False
        If False, return a copy. Otherwise, do operation
        in place and return None.
    errors : {'ignore', 'raise'}, default 'raise'
        If 'ignore', suppress error and only existing labels are
        dropped.

    Returns
    -------
    DataFrame or None
        Returns DataFrame or None DataFrame with the specified
        index or column labels removed or None if inplace=True.

    Raises
    ------
    KeyError
        If any of the labels is not found in the selected axis.

    See Also
    --------
    DataFrame.loc : Label-location based indexer for selection by label.
    DataFrame.dropna : Return DataFrame with labels on given axis omitted
        where (all or any) data are missing.
    DataFrame.drop_duplicates : Return DataFrame with duplicate rows
        removed, optionally only considering certain columns.
    Series.drop : Return Series with specified index labels removed.

    Examples
    --------
    >>> df = pd.DataFrame(np.arange(12).reshape(3, 4),
    ...                   columns=['A', 'B', 'C', 'D'])
    >>> df
       A  B   C   D
    0  0  1   2   3
    1  4  5   6   7
    2  8  9  10  11

    Drop columns

    >>> df.drop(['B', 'C'], axis=1)
       A   D
    0  0   3
    1  4   7
    2  8  11

    >>> df.drop(columns=['B', 'C'])
       A   D
    0  0   3
    1  4   7
    2  8  11

    Drop a row by index

    >>> df.drop([0, 1])
       A  B   C   D
    2  8  9  10  11

    Drop columns and/or rows of MultiIndex DataFrame

    >>> midx = pd.MultiIndex(levels=[['llama', 'cow', 'falcon'],
    ...                              ['speed', 'weight', 'length']],
    ...                      codes=[[0, 0, 0, 1, 1, 1, 2, 2, 2],
    ...                             [0, 1, 2, 0, 1, 2, 0, 1, 2]])
    >>> df = pd.DataFrame(index=midx, columns=['big', 'small'],
    ...                   data=[[45, 30], [200, 100], [1.5, 1], [30, 20],
    ...                         [250, 150], [1.5, 0.8], [320, 250],
    ...                         [1, 0.8], [0.3, 0.2]])
    >>> df
                    big     small
    llama   speed   45.0    30.0
            weight  200.0   100.0
            length  1.5     1.0
    cow     speed   30.0    20.0
            weight  250.0   150.0
            length  1.5     0.8
    falcon  speed   320.0   250.0
            weight  1.0     0.8
            length  0.3     0.2

    Drop a specific index combination from the MultiIndex
    DataFrame, i.e., drop the combination ``'falcon'`` and
    ``'weight'``, which deletes only the corresponding row

    >>> df.drop(index=('falcon', 'weight'))
                    big     small
    llama   speed   45.0    30.0
            weight  200.0   100.0
            length  1.5     1.0
    cow     speed   30.0    20.0
            weight  250.0   150.0
            length  1.5     0.8
    falcon  speed   320.0   250.0
            length  0.3     0.2

    >>> df.drop(index='cow', columns='small')
                    big
    llama   speed   45.0
            weight  200.0
            length  1.5
    falcon  speed   320.0
            weight  1.0
            length  0.3

    >>> df.drop(index='length', level=1)
                    big     small
    llama   speed   45.0    30.0
            weight  200.0   100.0
    cow     speed   30.0    20.0
            weight  250.0   150.0
    falcon  speed   320.0   250.0
            weight  1.0     0.8

In [5]:
sub_set_df = df.drop(columns=['Interest'])
sub_set_df

    Principal  Inflation
0       33593       0.05
1       36045       0.08
2       10034       0.09
3       57439       0.09
4       95748       0.04
..        ...        ...
95      68991       0.06
96      35120       0.04
97      32031       0.07
98      63019       0.03
99      26990       0.04

[100 rows x 2 columns]

In [6]:
correct_interest = sub_set_df.Principal * sub_set_df.Inflation
correct_interest

0     1679.65
1     2883.60
2      903.06
3     5169.51
4     3829.92
       ...
95    4139.46
96    1404.80
97    2242.17
98    1890.57
99    1079.60
Length: 100, dtype: float64

In [10]:
# Name it CorrectInterest
correct_interest.name = 'CorrectInterest'
correct_interest

0     1679.65
1     2883.60
2      903.06
3     5169.51
4     3829.92
       ...
95    4139.46
96    1404.80
97    2242.17
98    1890.57
99    1079.60
Name: CorrectInterest, Length: 100, dtype: float64

```py
my_df.some_column # some series
my_df['some_column'] # same thing

[my_df, my_other_df] # List of two dataframes
['my_df', 'my_other_df'] # List of two strings
```

In [13]:
new_df = pd.concat([sub_set_df, correct_interest], axis=1)
new_df

    Principal  Inflation  CorrectInterest
0       33593       0.05          1679.65
1       36045       0.08          2883.60
2       10034       0.09           903.06
3       57439       0.09          5169.51
4       95748       0.04          3829.92
..        ...        ...              ...
95      68991       0.06          4139.46
96      35120       0.04          1404.80
97      32031       0.07          2242.17
98      63019       0.03          1890.57
99      26990       0.04          1079.60

[100 rows x 3 columns]